function test_smartLabel
%TEST_SMARTLABEL  Verify bosonPlotter.smartLabel and its helpers.
%   Covers greekify (Greek substitution), unitSuperscript (sub/superscript
%   rendering), and abbreviateVariable (variable-name → symbol mapping),
%   plus the integrated smartLabel orchestrator.

    fprintf('\n=== test_smartLabel ===\n');
    nPass = 0; nFail = 0;

    % ── greekify ───────────────────────────────────────────────────────
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.greekify('2theta'),  '2θ',  'greekify 2theta');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.greekify('Theta'),    'θ',   'greekify case-insensitive');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.greekify('mu0'),      'μ0',  'greekify mu0');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.greekify('formula'),  'formula', 'greekify boundary-guarded');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.greekify('deg'),      '°',   'greekify deg');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.greekify('degrees'),  '°',   'greekify plural before singular');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.greekify(''),         '',    'greekify empty');

    % ── unitSuperscript ────────────────────────────────────────────────
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript('cm-1'),     'cm⁻¹',  'unit cm-1');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript('m^2'),      'm²',    'unit m^2');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript('Å^{-2}'),   'Å⁻²',   'unit braced exponent');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript('K^-1'),     'K⁻¹',   'unit caret negative');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript('10^{-6}'),  '10⁻⁶',  'unit prefactor');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript('H_2O'),     'H₂O',   'subscript');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript(''),         '',      'unit empty');
    % Idempotent: already-converted should pass through
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.unitSuperscript('cm⁻¹'),     'cm⁻¹',  'unit idempotent');

    % ── abbreviateVariable ─────────────────────────────────────────────
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.abbreviateVariable('Temperature'),    'T',  'abbrev Temperature');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.abbreviateVariable('Magnetic Field'), 'H',  'abbrev Magnetic Field');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.abbreviateVariable('temperature'),    'T',  'abbrev case-insensitive');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.abbreviateVariable('Applied Magnetic Field'), 'Applied Magnetic Field', ...
        'abbrev whole-string only');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.abbreviateVariable('Sample Temperature'), 'Sample Temperature', ...
        'abbrev no partial match');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.abbreviateVariable('Resistivity'), 'ρ', 'abbrev Resistivity → ρ');

    % ── smartLabel integration ─────────────────────────────────────────
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('Temperature', 'K'),   'Temperature (K)', ...
        'smartLabel default no abbrev');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('Temperature', 'K', Abbreviate=true), 'T (K)', ...
        'smartLabel abbreviated');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('2theta', 'deg'),      '2θ (°)', ...
        'smartLabel Greek + degree');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('Wavenumber', 'cm-1'), 'Wavenumber (cm⁻¹)', ...
        'smartLabel ASCII unit superscript');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('SLD', '10^{-6} Å^{-2}'), 'SLD (10⁻⁶ Å⁻²)', ...
        'smartLabel reflectivity SLD');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('Moment', 'emu'),      'Moment (emu)', ...
        'smartLabel passthrough');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('Magnetic Field', 'Oe', Abbreviate=true), 'H (Oe)', ...
        'smartLabel Magnetic Field abbreviated');
    [nPass, nFail] = check(nPass, nFail, ...
        bosonPlotter.smartLabel('Time', '', Abbreviate=true), 't', ...
        'smartLabel name-only');

    fprintf('\n%d passed, %d failed\n', nPass, nFail);
    if nFail > 0
        error('test_smartLabel: %d failures', nFail);
    end
end


function [nPass, nFail] = check(nPass, nFail, actual, expected, label)
    if strcmp(actual, expected)
        nPass = nPass + 1;
        fprintf('  PASS: %s\n', label);
    else
        nFail = nFail + 1;
        fprintf('  FAIL: %s\n    expected: %s\n    actual:   %s\n', ...
            label, expected, actual);
    end
end
