function s = buildCorrectionsPanel(parent, tk, palette, callbacks)
%BUILDCORRECTIONSPANEL  Corrections sub-panel for BosonPlotter (analysisGL col 1).
%
%   s = bosonPlotter.buildCorrectionsPanel(parent, tk, palette, callbacks)
%
%   Builds the 29-row × 4-col corrections sub-panel with collapsible
%   sections:
%     row  1 : Style dropdown + Live Preview checkbox
%     row  2 : Advanced Analysis button
%     row  3 : [HEADER] Offsets & Background (open by default)
%     rows 4-7: X/Y offset, BG slope/intercept, BG order/interp, Fit BG /
%              Y-pick / XRD peak tools
%     row  8 : [HEADER] Processing (open by default)
%     rows 9-12: smoothing, normalize, derivative, X trim, baseline
%               method + apply
%     row 13 : Baseline params (ALS λ / Rolling Ball radius; hidden unless
%              method needs them)
%     row 14 : (reserved)
%     row 15 : [HEADER] BG File Subtraction (collapsed by default) +
%              region stats label
%     rows 16-17: BG file controls + subtract toggle
%     rows 18-19: Spin asymmetry (neutron only, RowHeight=0 otherwise)
%     row 20 : [HEADER] Sample & Units (magnetometry, collapsed by default)
%     rows 21-25: mass / dim / thick / unit-system / auto BG+offset
%     rows 26-29: Apply / Reset / Show Raw, Apply-to-All / Undo / Redo,
%                 Mask Select / Hide / Unmask, presets dropdown + save +
%                 delete
%
%   Inputs
%     parent     uigridlayout (analysisGL) where corrPanel is parented
%     tk         UX tokens (tk.font.*, tk.pad.*, tk.color.*)
%     palette    struct of semantic button colors:
%                  .primary, .accent, .danger, .tool, .interact, .fg
%     callbacks  struct of function handles — see usage in body. The
%                builder also expects callbacks.markCorrectionsDirty
%                because many edit-fields call it on ValueChangedFcn.
%
%   Output
%     s          struct of widget handles + the CROW row-constant struct.
%                The caller unpacks into the same local variables the rest
%                of BosonPlotter.m references.

    arguments
        parent
        tk         struct
        palette    struct
        callbacks  struct
    end

    s.corrPanel = uipanel(parent, 'Title', 'Corrections', ...
        'FontSize', tk.font.title, 'Scrollable', 'on');
    s.corrPanel.Layout.Row = [1 2]; s.corrPanel.Layout.Column = 1;

    s.CROW = struct( ...
        'STYLE',      1,  'ADVANCED',  2,  'SEC_OFFSETS', 3,  'XOFF',       4,  'YOFF',       5, ...
        'BGORDER',    6,  'TOOLS',     7,  'SEC_PROC',   8,  'SMOOTH',     9, ...
        'NORM_DERIV',10,  'TRIM',     11,  'BASELINE',  12, ...
        'BASELINE_PARAMS', 13,  'BASELINE_APPLY', 14, ...
        'SEC_BGFILE', 15, ...
        'BGFILE',    16,  'BGSUBTR',  17,  'ASYM1',     18,  'ASYM2',     19, ...
        'SEC_MAG',   20,  'MAG_MASS', 21,  'MAG_DIM',   22,  'MAG_THICK', 23, ...
        'MAG_UNITS', 24,  'MAG_AUTO', 25, ...
        'APPLY',     26,  'ACTIONS',  27,  'MASK',   28,  'REDO',  29);
    CROW = s.CROW;

    s.corrGL = uigridlayout(s.corrPanel, [29 4], ...
        'RowHeight',    {24, 24, 20, 22,22,22,22, 20, 22,22,22,22, 0,0, 20, 0,0, 0,0, ...
                         0,0,0,0,0,0, 24,22, 22, 22}, ...
        'ColumnWidth',  {80,'1x',80,'1x'}, ...
        'Padding',      tk.pad.normal, ...
        'RowSpacing',   2, ...
        'ColumnSpacing', 3);

    % Row 1: Correction style + Live preview
    lbl = uilabel(s.corrGL, 'Text', 'Style:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.STYLE; lbl.Layout.Column = 1;

    s.ddCorrStyle = uidropdown(s.corrGL, ...
        'Items', {'Auto (from file)', 'Generic', 'Magnetometry', 'PPMS', 'XRD — 2\theta + BG', 'Neutron NR', 'SIMS Depth Profile'}, ...
        'Value', 'Auto (from file)', ...
        'Tooltip', ['Controls which correction tools and analysis features are shown. ' ...
            '"Auto" detects from the file type. "XRD" enables peak detection. ' ...
            '"Neutron NR" enables spin asymmetry. "Generic" shows all controls.'], ...
        'ValueChangedFcn', callbacks.onCorrStyleChanged);
    s.ddCorrStyle.Layout.Row = CROW.STYLE; s.ddCorrStyle.Layout.Column = [2 3];

    % Apply mode (replaces the old "Live" + "Auto-Apply" checkbox pair —
    % they did almost the same thing with confusing labels).
    %   Manual — Apply Corrections only fires on button click
    %   Auto   — debounced 0.3 s after each parameter change
    %   Live   — re-apply + redraw immediately on each change
    s.ddApplyMode = uidropdown(s.corrGL, ...
        'Items', {'Manual', 'Auto', 'Live'}, 'Value', 'Live', ...
        'Tooltip', ['How parameter changes propagate to the plot. ' ...
                    'Manual = wait for Apply click; Auto = debounced 0.3 s; ' ...
                    'Live = immediate (uncheck for large/slow datasets).'], ...
        'ValueChangedFcn', callbacks.updateApplyButtonStyle);
    s.ddApplyMode.Layout.Row = CROW.STYLE; s.ddApplyMode.Layout.Column = 4;

    % Row 2: Tools menu (de-emphasized — primary access is now via the top
    % menu bar; this stays as a panel-local shortcut, secondary palette).
    s.btnAdvancedCorr = uibutton(s.corrGL, 'Text', ['Tools ' char(9662)], ...
        'ButtonPushedFcn', callbacks.onShowAdvancedMenu, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, ...
        'FontSize', tk.font.label, ...
        'Tooltip', 'Open advanced analysis menu: Integrate, Curve Fit, Dataset Math, Digitizer, Resample…');
    s.btnAdvancedCorr.Layout.Row = CROW.ADVANCED; s.btnAdvancedCorr.Layout.Column = [3 4];

    % Row 3: Section header — Offsets & Background
    s.lblSecOffsets = bosonPlotter.sectionHeader(s.corrGL, [char(9660) ' Offsets & BG'], ...
        callbacks.toggleOffsets, ...
        'BackgroundColor', s.corrGL.BackgroundColor, 'FontColor', tk.color.textDim);
    s.lblSecOffsets.Layout.Row = CROW.SEC_OFFSETS; s.lblSecOffsets.Layout.Column = [1 4];

    % Row 4: X Offset | BG Slope (labels are kept on s because
    % applyParserAnalysisConfig relabels them at runtime per parser type)
    s.lblXOff = uilabel(s.corrGL, 'Text', 'X Offset:', 'HorizontalAlignment', 'right');
    s.lblXOff.Layout.Row = CROW.XOFF; s.lblXOff.Layout.Column = 1;
    s.efXOffset = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Tooltip', 'X-offset: x_corrected = x − this value (0 = no shift)', ...
        'Limits', [-Inf Inf], 'LowerLimitInclusive', 'off', 'UpperLimitInclusive', 'off', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.efXOffset.Layout.Row = CROW.XOFF; s.efXOffset.Layout.Column = 2;

    s.lblBGSlope = uilabel(s.corrGL, 'Text', 'BG Slope:', 'HorizontalAlignment', 'right');
    s.lblBGSlope.Layout.Row = CROW.XOFF; s.lblBGSlope.Layout.Column = 3;
    s.efBGSlope = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Tooltip', 'Linear BG slope m: y_BG = m·x + b  (0 = no BG subtraction)', ...
        'Limits', [-Inf Inf], 'LowerLimitInclusive', 'off', 'UpperLimitInclusive', 'off', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.efBGSlope.Layout.Row = CROW.XOFF; s.efBGSlope.Layout.Column = 4;

    % Row 5: Y Offset | BG Intercept (labels relabelled at runtime)
    s.lblYOff = uilabel(s.corrGL, 'Text', 'Y Offset:', 'HorizontalAlignment', 'right');
    s.lblYOff.Layout.Row = CROW.YOFF; s.lblYOff.Layout.Column = 1;
    s.efYOffset = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Tooltip', 'Y-offset: applied after BG subtraction  (0 = no shift)', ...
        'Limits', [-Inf Inf], 'LowerLimitInclusive', 'off', 'UpperLimitInclusive', 'off', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.efYOffset.Layout.Row = CROW.YOFF; s.efYOffset.Layout.Column = 2;

    s.lblBGInt = uilabel(s.corrGL, 'Text', 'BG Intercept:', 'HorizontalAlignment', 'right');
    s.lblBGInt.Layout.Row = CROW.YOFF; s.lblBGInt.Layout.Column = 3;
    s.efBGIntercept = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Tooltip', 'Linear BG intercept b: y_BG = m·x + b  (0 = no BG subtraction)', ...
        'Limits', [-Inf Inf], 'LowerLimitInclusive', 'off', 'UpperLimitInclusive', 'off', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.efBGIntercept.Layout.Row = CROW.YOFF; s.efBGIntercept.Layout.Column = 4;

    % Row 6: BG Order | BG Interp
    lbl = uilabel(s.corrGL, 'Text', 'BG Order:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.BGORDER; lbl.Layout.Column = 1;
    s.ddBGOrder = uidropdown(s.corrGL, ...
        'Items', {'Linear', 'Poly 2', 'Poly 3', 'Poly 4', 'Poly 5', 'Poly 6'}, 'Value', 'Linear', ...
        'Tooltip', 'Polynomial order used by "Fit BG from Box": Linear=1st-order, Poly N=Nth-order');
    s.ddBGOrder.Layout.Row = CROW.BGORDER; s.ddBGOrder.Layout.Column = 2;

    lbl = uilabel(s.corrGL, 'Text', 'Interp:', 'HorizontalAlignment', 'right', 'FontSize', tk.font.label);
    lbl.Layout.Row = CROW.BGORDER; lbl.Layout.Column = 3;
    s.ddBGInterp = uidropdown(s.corrGL, ...
        'Items', {'linear', 'pchip', 'spline', 'nearest'}, 'Value', 'linear', ...
        'Tooltip', 'Interpolation method for background subtraction: linear (default), pchip (smooth), spline (smoother), nearest (step)', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.ddBGInterp.Layout.Row = CROW.BGORDER; s.ddBGInterp.Layout.Column = 4;

    % Row 7: Interactive tools (generic + XRD-mode hidden alternatives)
    s.btnFitBG = uibutton(s.corrGL, 'Text', 'Fit BG from Box', ...
        'ButtonPushedFcn', callbacks.onFitBGRegion, ...
        'BackgroundColor', palette.interact, 'FontColor', [1 1 1], ...
        'Tooltip', ['Draw a rectangle on the preview axes.  ' ...
                    'All selected-Y data points inside the box are fitted with ' ...
                    'a polynomial of the order chosen in "BG Order" (Linear = 1st-order).  ' ...
                    'For Linear: BG Slope and Intercept are auto-populated.  ' ...
                    'For higher orders: polynomial is stored per-dataset and applied on corrections.']);
    s.btnFitBG.Layout.Row = CROW.TOOLS; s.btnFitBG.Layout.Column = [1 2];

    s.btnPickY = uibutton(s.corrGL, 'Text', 'Est. Y Offset  (2 pts)', ...
        'ButtonPushedFcn', callbacks.onPickYOrigin, ...
        'BackgroundColor', [0.45 0.20 0.55], 'FontColor', [1 1 1], ...
        'Tooltip', ['Click two data points on the plot.  ' ...
                    'The Y Offset is updated so that y = 0 falls halfway ' ...
                    'between their y-values.  Works on whichever data is ' ...
                    'currently displayed (raw or corrected).']);
    s.btnPickY.Layout.Row = CROW.TOOLS; s.btnPickY.Layout.Column = [3 4];

    s.btnYTranslate = uibutton(s.corrGL, 'Text', 'Y Translate (drag)', ...
        'ButtonPushedFcn', callbacks.onYTranslateDrag, ...
        'BackgroundColor', palette.accent, 'FontColor', palette.fg, ...
        'Tooltip', ['Click and drag up/down on the plot to shift the data ' ...
                    'vertically — updates Y Offset live on each mouse move.'], ...
        'Visible', 'off');
    s.btnYTranslate.Layout.Row = CROW.TOOLS; s.btnYTranslate.Layout.Column = [1 2];

    s.btnAutoPeak = uibutton(s.corrGL, 'Text', 'Auto Find Peaks', ...
        'ButtonPushedFcn', @(~,~)[], ...
        'BackgroundColor', palette.interact, 'FontColor', [1 1 1], ...
        'Tooltip', 'Detect peaks automatically using SNIP background estimation and SNR-based filtering', ...
        'Visible', 'off');
    s.btnAutoPeak.Layout.Row = CROW.TOOLS; s.btnAutoPeak.Layout.Column = 3;

    s.btnManualPeak = uibutton(s.corrGL, 'Text', 'Add Peak', ...
        'ButtonPushedFcn', @(~,~)[], ...
        'BackgroundColor', [0.45 0.20 0.55], 'FontColor', [1 1 1], ...
        'Tooltip', 'Click once on a peak in the plot to add it to the peak list (click button again to finish)', ...
        'Visible', 'off');
    s.btnManualPeak.Layout.Row = CROW.TOOLS; s.btnManualPeak.Layout.Column = 4;

    s.btnRemovePeakClick = uibutton(s.corrGL, 'Text', 'Click-Rm', ...
        'ButtonPushedFcn', @(~,~)[], ...
        'BackgroundColor', palette.danger, 'FontColor', palette.fg, ...
        'FontSize', tk.font.body, ...
        'Tooltip', 'Click on a peak marker in the plot to remove it (click button again to finish)', ...
        'Visible', 'off');
    s.btnRemovePeakClick.Layout.Row = CROW.BGORDER; s.btnRemovePeakClick.Layout.Column = 3;

    s.btnPeakWindow = uibutton(s.corrGL, 'Text', 'Peaks', ...
        'ButtonPushedFcn', callbacks.showPeakWindow, ...
        'BackgroundColor', palette.accent, 'FontColor', palette.fg, ...
        'FontSize', tk.font.body, ...
        'Tooltip', 'Open the Peak Analysis window (table, fitting, export)', ...
        'Visible', 'off');
    s.btnPeakWindow.Layout.Row = CROW.BGORDER; s.btnPeakWindow.Layout.Column = 4;

    % Row 8: Section header — Processing
    s.lblSecProc = bosonPlotter.sectionHeader(s.corrGL, [char(9660) ' Processing'], ...
        callbacks.toggleProcessing, ...
        'BackgroundColor', s.corrGL.BackgroundColor, 'FontColor', tk.color.textDim);
    s.lblSecProc.Layout.Row = CROW.SEC_PROC; s.lblSecProc.Layout.Column = [1 4];

    % Row 9: Smoothing
    s.cbSmooth = uicheckbox(s.corrGL, 'Text', 'Smooth', 'Value', false, ...
        'Tooltip', 'Apply smoothing to corrected data when Apply Corrections is pressed', ...
        'ValueChangedFcn', callbacks.onSmoothingChanged);
    s.cbSmooth.Layout.Row = CROW.SMOOTH; s.cbSmooth.Layout.Column = 1;

    s.efSmoothWin = uieditfield(s.corrGL, 'numeric', 'Value', 5, ...
        'Limits', [1 Inf], 'LowerLimitInclusive', 'on', 'RoundFractionalValues', 'on', ...
        'Tooltip', 'Smoothing half-window in samples (total width = 2W+1 points)', ...
        'ValueChangedFcn', callbacks.onSmoothingChanged);
    s.efSmoothWin.Layout.Row = CROW.SMOOTH; s.efSmoothWin.Layout.Column = 2;

    s.ddSmoothMethod = uidropdown(s.corrGL, ...
        'Items', {'Moving', 'Gaussian', 'Savitzky-Golay'}, 'Value', 'Moving', ...
        'Tooltip', ['Moving: uniform average  |  Gaussian: bell-curve weighted  |  ' ...
                    'Savitzky-Golay: polynomial fit (preserves peak shapes)'], ...
        'ValueChangedFcn', callbacks.onSmoothingChanged);
    s.ddSmoothMethod.Layout.Row = CROW.SMOOTH; s.ddSmoothMethod.Layout.Column = 3;

    s.cbSmoothPreview = uicheckbox(s.corrGL, 'Text', 'Preview', 'Value', false, ...
        'Tooltip', ['Show a live dashed overlay of smoothed data on the plot without modifying ' ...
                    'the dataset. Uncheck or click Apply to remove the overlay.'], ...
        'ValueChangedFcn', callbacks.onSmoothPreviewToggled);
    s.cbSmoothPreview.Layout.Row = CROW.SMOOTH; s.cbSmoothPreview.Layout.Column = 4;

    % Row 10: Normalize | Derivative
    lbl = uilabel(s.corrGL, 'Text', 'Norm:', 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.NORM_DERIV; lbl.Layout.Column = 1;
    s.ddNormalize = uidropdown(s.corrGL, ...
        'Items', {'None', 'Range [0,1]', 'Peak (max=1)', 'Z-score', 'Area (integral=1)'}, 'Value', 'None', ...
        'Tooltip', 'Normalize corrected data: Range = [0,1], Peak = max height = 1, Z-score = (x-mean)/std, Area = integrate to 1', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.ddNormalize.Layout.Row = CROW.NORM_DERIV; s.ddNormalize.Layout.Column = 2;

    lbl = uilabel(s.corrGL, 'Text', 'Deriv:', 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.NORM_DERIV; lbl.Layout.Column = 3;
    s.ddDerivative = uidropdown(s.corrGL, ...
        'Items', {'None', 'dY/dX', 'd²Y/dX²', '∫Y dx', 'dlog/dlog'}, 'Value', 'None', ...
        'Tooltip', ['Transforms: dY/dX, d²Y/dX² (derivatives), ' ...
                    char(8747) 'Y dx (cumulative integral), ' ...
                    'dlog/dlog (log derivative — power-law exponent).'], ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.ddDerivative.Layout.Row = CROW.NORM_DERIV; s.ddDerivative.Layout.Column = 4;

    % Row 11: X trim — labeled min/max placeholders so the two fields aren't
    % visually anonymous siblings.
    lbl = uilabel(s.corrGL, 'Text', 'Trim X:', 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.TRIM; lbl.Layout.Column = 1;
    s.efXTrimMin = uieditfield(s.corrGL, 'text', 'Value', '', ...
        'Placeholder', 'min', ...
        'Tooltip', 'Trim x-range: keep only data from this minimum x-value (blank = no limit)', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.efXTrimMin.Layout.Row = CROW.TRIM; s.efXTrimMin.Layout.Column = 2;
    s.efXTrimMax = uieditfield(s.corrGL, 'text', 'Value', '', ...
        'Placeholder', 'max', ...
        'Tooltip', 'Trim x-range: keep only data up to this maximum x-value (blank = no limit)', ...
        'ValueChangedFcn', callbacks.markCorrectionsDirty);
    s.efXTrimMax.Layout.Row = CROW.TRIM; s.efXTrimMax.Layout.Column = [3 4];

    % Row 12: Baseline method
    lbl = uilabel(s.corrGL, 'Text', 'Baseline:', 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.BASELINE; lbl.Layout.Column = 1;
    s.ddBaselineMethod = uidropdown(s.corrGL, ...
        'Items', {'SNIP', 'ALS', 'Rolling Ball', 'Mod. Polynomial'}, 'Value', 'SNIP', ...
        'Tooltip', ['SNIP: peak-clipping (best for XRD)  |  ALS: asymmetric least squares ' ...
                    '(Raman, EELS)  |  Rolling Ball: morphological lower envelope  |  ' ...
                    'Mod. Polynomial: iterative polynomial fit (fluorescence removal)'], ...
        'ValueChangedFcn', callbacks.onBaselineMethodChanged);
    s.ddBaselineMethod.Layout.Row = CROW.BASELINE; s.ddBaselineMethod.Layout.Column = [2 3];

    s.btnEstimateBaseline = uibutton(s.corrGL, 'Text', 'Apply', ...
        'ButtonPushedFcn', callbacks.onEstimateBaseline, ...
        'Tooltip', 'Estimate and subtract baseline using the selected method', ...
        'FontSize', tk.font.body);
    s.btnEstimateBaseline.Layout.Row = CROW.BASELINE; s.btnEstimateBaseline.Layout.Column = 4;

    % Row 13: Baseline params (ALS λ / Rolling Ball radius — hidden by default)
    s.lblBaselineLambda = uilabel(s.corrGL, 'Text', [char(955) ' (ALS):'], 'HorizontalAlignment', 'right', ...
        'Tooltip', 'ALS smoothness penalty (default 1e6 — larger = smoother baseline)');
    s.lblBaselineLambda.Layout.Row = CROW.BASELINE_PARAMS; s.lblBaselineLambda.Layout.Column = 1;
    s.efBaselineLambda = uieditfield(s.corrGL, 'numeric', 'Value', 1e6, ...
        'Limits', [1 Inf], 'LowerLimitInclusive', 'on', ...
        'Tooltip', 'ALS lambda: smoothness penalty (1e4–1e9 typical; default 1e6)', ...
        'ValueChangedFcn', @(~,~) []);
    s.efBaselineLambda.Layout.Row = CROW.BASELINE_PARAMS; s.efBaselineLambda.Layout.Column = 2;

    s.lblBaselineRadius = uilabel(s.corrGL, 'Text', 'Radius:', 'HorizontalAlignment', 'right', ...
        'Tooltip', 'Rolling Ball radius in data points (default 100)');
    s.lblBaselineRadius.Layout.Row = CROW.BASELINE_PARAMS; s.lblBaselineRadius.Layout.Column = 3;
    s.efBaselineRadius = uieditfield(s.corrGL, 'numeric', 'Value', 100, ...
        'Limits', [1 Inf], 'LowerLimitInclusive', 'on', 'RoundFractionalValues', 'on', ...
        'Tooltip', 'Rolling Ball radius in data points (default 100; larger = smoother)', ...
        'ValueChangedFcn', @(~,~) []);
    s.efBaselineRadius.Layout.Row = CROW.BASELINE_PARAMS; s.efBaselineRadius.Layout.Column = 4;

    % Row 15: Section header — BG File Subtraction
    s.lblSecBGFile = bosonPlotter.sectionHeader(s.corrGL, [char(9654) ' BG File Subtraction'], ...
        callbacks.toggleBGFile, ...
        'BackgroundColor', s.corrGL.BackgroundColor, 'FontColor', tk.color.textDim);
    s.lblSecBGFile.Layout.Row = CROW.SEC_BGFILE; s.lblSecBGFile.Layout.Column = [1 4];

    % Region statistics readout — same row as the BG File header (cols 2-4)
    s.lblRegionStats = uilabel(s.corrGL, 'Text', '', 'FontSize', tk.font.body, ...
        'FontColor', tk.color.textAccent);
    s.lblRegionStats.Layout.Row = CROW.SEC_BGFILE; s.lblRegionStats.Layout.Column = [2 4];

    % Row 16: BG file picker
    lbl = uilabel(s.corrGL, 'Text', 'BG File:', 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.BGFILE; lbl.Layout.Column = 1;
    s.efBGFile = uieditfield(s.corrGL, 'text', 'Value', '', ...
        'Placeholder', '— none loaded —', 'Editable', 'off', ...
        'Tooltip', 'Loaded background dataset — use "Load BG..." to populate');
    s.efBGFile.Layout.Row = CROW.BGFILE; s.efBGFile.Layout.Column = 2;

    s.btnLoadBG = uibutton(s.corrGL, 'Text', 'Load BG', ...
        'ButtonPushedFcn', callbacks.onLoadBackground, ...
        'Tooltip', 'Load a background file (any supported format) to subtract from corrected data');
    s.btnLoadBG.Layout.Row = CROW.BGFILE; s.btnLoadBG.Layout.Column = 3;

    s.btnSetActiveBG = uibutton(s.corrGL, 'Text', 'Use Active', ...
        'ButtonPushedFcn', callbacks.onSetActiveBG, ...
        'Tooltip', 'Use the active dataset as the background (no file dialog needed)', ...
        'FontSize', tk.font.body);
    s.btnSetActiveBG.Layout.Row = CROW.BGFILE; s.btnSetActiveBG.Layout.Column = 4;

    % Row 17: Subtract BG toggle + Clear
    s.cbSubtractBG = uicheckbox(s.corrGL, 'Text', 'Subtract BG', 'Value', false, ...
        'Tooltip', 'Subtract the loaded background from corrected data when Apply Corrections is pressed');
    s.cbSubtractBG.Layout.Row = CROW.BGSUBTR; s.cbSubtractBG.Layout.Column = [1 2];

    s.btnClearBG = uibutton(s.corrGL, 'Text', 'Clear BG', ...
        'ButtonPushedFcn', callbacks.onClearBackground, ...
        'Tooltip', 'Remove the currently loaded background dataset');
    s.btnClearBG.Layout.Row = CROW.BGSUBTR; s.btnClearBG.Layout.Column = [3 4];

    % Row 18: Spin asymmetry (neutron only) — first cell carries the
    % "Spin Asymmetry" section title so users know what the next two rows
    % belong to when they appear.
    lbl = uilabel(s.corrGL, 'Text', 'Spin Asymmetry', ...
        'FontWeight', 'bold', 'FontColor', tk.color.textDim, ...
        'HorizontalAlignment', 'left');
    lbl.Layout.Row = CROW.ASYM1; lbl.Layout.Column = 1;
    s.cbCalculateAsymmetry = uicheckbox(s.corrGL, 'Text', 'Calculate & Plot', 'Value', false, ...
        'Tooltip', 'Calculate spin asymmetry (R++ − R--) / (R++ + R--) and plot as new channel', ...
        'ValueChangedFcn', callbacks.onAsymmetryToggle);
    s.cbCalculateAsymmetry.Layout.Row = CROW.ASYM1; s.cbCalculateAsymmetry.Layout.Column = [2 4];

    % Row 19: Asymmetry formula
    lbl = uilabel(s.corrGL, 'Text', 'Formula:', 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.ASYM2; lbl.Layout.Column = 1;
    s.ddAsymFormula = uidropdown(s.corrGL, ...
        'Items', {'Linear: (R++ − R--) / (R++ + R--)', 'Log: log(R++ / R--)'}, ...
        'Value', 'Linear: (R++ − R--) / (R++ + R--)', ...
        'Tooltip', 'Asymmetry formula: Linear uses reflectivity ratio, Log uses reflectivity ratio logarithm');
    s.ddAsymFormula.Layout.Row = CROW.ASYM2; s.ddAsymFormula.Layout.Column = [2 4];

    % Row 20: Magnetometry section header
    s.lblSecMag = bosonPlotter.sectionHeader(s.corrGL, [char(9654) ' Sample & Units'], ...
        callbacks.toggleMagSample, ...
        'BackgroundColor', s.corrGL.BackgroundColor, 'FontColor', tk.color.textDim);
    s.lblSecMag.Layout.Row = CROW.SEC_MAG; s.lblSecMag.Layout.Column = [1 4];

    % Row MAG_MASS: Mass | Unit system
    lbl = uilabel(s.corrGL, 'Text', 'Mass (g):', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.MAG_MASS; lbl.Layout.Column = 1;
    s.efSampleMass = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Limits', [0 Inf], 'LowerLimitInclusive', 'on', 'ValueDisplayFormat', '%.6g', ...
        'Tooltip', 'Sample mass in grams (for emu/g normalization; 0 = not set)');
    s.efSampleMass.Layout.Row = CROW.MAG_MASS; s.efSampleMass.Layout.Column = 2;

    lbl = uilabel(s.corrGL, 'Text', 'Units:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.MAG_MASS; lbl.Layout.Column = 3;
    s.ddUnitSystem = uidropdown(s.corrGL, ...
        'Items', {'CGS', 'SI'}, 'Value', 'CGS', ...
        'Tooltip', 'Quick-set CGS (Oe + emu) or SI (T + A·m²) — updates Field & Moment dropdowns below', ...
        'ValueChangedFcn', callbacks.onUnitSystemChanged);
    s.ddUnitSystem.Layout.Row = CROW.MAG_MASS; s.ddUnitSystem.Layout.Column = 4;

    % Row MAG_DIM: W × H + dimension unit
    lbl = uilabel(s.corrGL, 'Text', 'W × H:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.MAG_DIM; lbl.Layout.Column = 1;
    s.efSampleWidth = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Limits', [0 Inf], 'LowerLimitInclusive', 'on', 'ValueDisplayFormat', '%.6g', ...
        'Tooltip', 'Sample width (for volume calculation; 0 = not set)');
    s.efSampleWidth.Layout.Row = CROW.MAG_DIM; s.efSampleWidth.Layout.Column = 2;

    s.efSampleHeight = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Limits', [0 Inf], 'LowerLimitInclusive', 'on', 'ValueDisplayFormat', '%.6g', ...
        'Tooltip', 'Sample height (for volume calculation; 0 = not set)');
    s.efSampleHeight.Layout.Row = CROW.MAG_DIM; s.efSampleHeight.Layout.Column = 3;

    s.ddDimUnit = uidropdown(s.corrGL, ...
        'Items', {'mm', 'cm'}, 'Value', 'mm', ...
        'Tooltip', 'Unit for width and height dimensions (mm or cm)');
    s.ddDimUnit.Layout.Row = CROW.MAG_DIM; s.ddDimUnit.Layout.Column = 4;

    % Row MAG_THICK: Thickness + thickness unit
    lbl = uilabel(s.corrGL, 'Text', 'Thickness:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.MAG_THICK; lbl.Layout.Column = 1;
    s.efSampleThick = uieditfield(s.corrGL, 'numeric', 'Value', 0, ...
        'Limits', [0 Inf], 'LowerLimitInclusive', 'on', 'ValueDisplayFormat', '%.6g', ...
        'Tooltip', 'Sample thickness (for volume calculation; 0 = not set)');
    s.efSampleThick.Layout.Row = CROW.MAG_THICK; s.efSampleThick.Layout.Column = 2;

    lbl = uilabel(s.corrGL, 'Text', 'Thick. Unit:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.MAG_THICK; lbl.Layout.Column = 3;
    s.ddThickUnit = uidropdown(s.corrGL, ...
        'Items', {'nm', char(197)}, 'Value', 'nm', ...
        'Tooltip', ['Thickness unit: nm or ' char(197) ' (Angstrom)']);
    s.ddThickUnit.Layout.Row = CROW.MAG_THICK; s.ddThickUnit.Layout.Column = 4;

    % Row MAG_UNITS: Field unit | Moment unit
    lbl = uilabel(s.corrGL, 'Text', 'Field:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.MAG_UNITS; lbl.Layout.Column = 1;
    s.ddFieldUnit = uidropdown(s.corrGL, ...
        'Items', {'Oe', 'T', 'mT', 'A/m'}, 'Value', 'Oe', ...
        'Tooltip', 'Convert magnetic field x-axis units (Oe → T, mT, or A/m)', ...
        'ValueChangedFcn', callbacks.onMagUnitChanged);
    s.ddFieldUnit.Layout.Row = CROW.MAG_UNITS; s.ddFieldUnit.Layout.Column = 2;

    lbl = uilabel(s.corrGL, 'Text', 'Moment:', 'FontSize', tk.font.label, 'HorizontalAlignment', 'right');
    lbl.Layout.Row = CROW.MAG_UNITS; lbl.Layout.Column = 3;
    s.ddMomentUnit = uidropdown(s.corrGL, ...
        'Items', {'emu', 'emu/g', 'emu/cm³', 'A·m²', 'kA/m'}, 'Value', 'emu', ...
        'Tooltip', ['Normalize moment: emu/g (divide by mass), emu/cm' char(179) ...
                    ' (divide by volume), A' char(183) 'm' char(178) ' (SI moment), kA/m (SI magnetization)'], ...
        'ValueChangedFcn', callbacks.onMagUnitChanged);
    s.ddMomentUnit.Layout.Row = CROW.MAG_UNITS; s.ddMomentUnit.Layout.Column = 4;

    % Row MAG_AUTO: Auto BG+Y Off + scope dropdown
    s.btnAutoMagCorr = uibutton(s.corrGL, 'Text', 'Auto BG + Y Off', ...
        'ButtonPushedFcn', callbacks.onAutoMagCorrections, ...
        'BackgroundColor', [0.20 0.50 0.35], 'FontColor', palette.fg, ...
        'Tooltip', ['Estimate linear background slope and Y offset from data near ' ...
                    char(177) '95% of the max field range (high-field saturation region).  ' ...
                    'Sets BG Slope, Intercept, and Y Offset, then applies corrections.']);
    s.btnAutoMagCorr.Layout.Row = CROW.MAG_AUTO; s.btnAutoMagCorr.Layout.Column = [1 2];

    s.ddAutoMagScope = uidropdown(s.corrGL, ...
        'Items', {'Active', 'All Datasets'}, 'Value', 'Active', ...
        'Tooltip', 'Apply auto-correction to just the active dataset or all loaded magnetometry datasets');
    s.ddAutoMagScope.Layout.Row = CROW.MAG_AUTO; s.ddAutoMagScope.Layout.Column = [3 4];

    % Row 26: Apply | Reset | Show Raw  — Apply spans 2 cols so it reads as
    % the primary action; the old "Auto-Apply" checkbox was folded into the
    % Apply Mode dropdown at the top of the panel.
    s.btnApply = uibutton(s.corrGL, 'Text', 'Apply Corrections', ...
        'ButtonPushedFcn', callbacks.onApplyCorrections, ...
        'BackgroundColor', palette.primary, 'FontColor', palette.fg, 'FontWeight', 'bold', ...
        'Tooltip', 'Compute corrected data and update plot  [Ctrl+Enter]');
    s.btnApply.Layout.Row = CROW.APPLY; s.btnApply.Layout.Column = [1 2];

    s.btnReset = uibutton(s.corrGL, 'Text', 'Reset', ...
        'ButtonPushedFcn', callbacks.onResetCorrections, ...
        'Tooltip', 'Zero all correction fields and discard corrected data for the active dataset');
    s.btnReset.Layout.Row = CROW.APPLY; s.btnReset.Layout.Column = 3;

    s.cbShowRaw = uicheckbox(s.corrGL, 'Text', 'Show Raw', 'Value', true, ...
        'Tooltip', 'When corrected data exists, also overlay raw data (dashed, desaturated)', ...
        'ValueChangedFcn', callbacks.onShowRawToggled);
    s.cbShowRaw.Layout.Row = CROW.APPLY; s.cbShowRaw.Layout.Column = 4;

    % Row 27: Apply to All | Undo | Redo
    s.btnApplyAll = uibutton(s.corrGL, 'Text', 'Apply to All', ...
        'ButtonPushedFcn', callbacks.onApplyCorrectionsAll, ...
        'Tooltip', 'Copy current corrections to all loaded datasets', ...
        'FontColor', tk.color.textMuted, 'FontSize', tk.font.body);
    s.btnApplyAll.Layout.Row = CROW.ACTIONS; s.btnApplyAll.Layout.Column = [1 2];

    s.btnUndo = uibutton(s.corrGL, 'Text', [char(8617) ' Undo'], ...
        'ButtonPushedFcn', callbacks.onUndo, ...
        'Tooltip', 'Nothing to undo  [Ctrl+Z]', ...
        'FontColor', tk.color.textMuted, 'FontSize', tk.font.body);
    s.btnUndo.Layout.Row = CROW.ACTIONS; s.btnUndo.Layout.Column = 3;

    s.btnRedo = uibutton(s.corrGL, 'Text', [char(8618) ' Redo'], ...
        'ButtonPushedFcn', callbacks.onRedo, ...
        'Tooltip', 'Nothing to redo  [Ctrl+Y]', ...
        'FontColor', tk.color.textMuted, 'FontSize', tk.font.body, ...
        'Enable', 'off');
    s.btnRedo.Layout.Row = CROW.ACTIONS; s.btnRedo.Layout.Column = 4;

    % Row 28: Mask Selection | Hide | Unmask All
    s.btnMaskSelect = uibutton(s.corrGL, 'Text', 'Mask Selection', ...
        'ButtonPushedFcn', callbacks.onArmMaskSelection, ...
        'BackgroundColor', [0.60 0.15 0.15], 'FontColor', palette.fg, 'FontSize', tk.font.body, ...
        'Tooltip', 'Click & drag a rectangle on the plot to mask (exclude) data points inside the box');
    s.btnMaskSelect.Layout.Row = CROW.MASK; s.btnMaskSelect.Layout.Column = [1 2];

    s.btnToggleVis = uibutton(s.corrGL, 'Text', 'Hide', ...
        'ButtonPushedFcn', callbacks.onToggleDatasetVisibility, ...
        'Tooltip', 'Hide/show the active dataset in the plot without removing it  [Space]', ...
        'FontColor', tk.color.textMuted, 'FontSize', tk.font.body);
    s.btnToggleVis.Layout.Row = CROW.MASK; s.btnToggleVis.Layout.Column = 3;

    s.btnUnmaskAll = uibutton(s.corrGL, 'Text', 'Unmask All', ...
        'ButtonPushedFcn', callbacks.onUnmaskAll, ...
        'BackgroundColor', palette.tool, 'FontColor', tk.color.textMuted, 'FontSize', tk.font.body, ...
        'Tooltip', 'Restore all masked data points for the active dataset  [Ctrl+M]');
    s.btnUnmaskAll.Layout.Row = CROW.MASK; s.btnUnmaskAll.Layout.Column = 4;

    % Row 29: Correction presets — dropdown + Save + Delete
    s.ddPreset = uidropdown(s.corrGL, ...
        'Items', [{'(presets)'}, bosonPlotter.correctionPresets.list()], 'Value', '(presets)', ...
        'FontSize', tk.font.body, ...
        'Tooltip', 'Load a saved set of correction parameters', ...
        'ValueChangedFcn', callbacks.onLoadPreset);
    s.ddPreset.Layout.Row = CROW.REDO; s.ddPreset.Layout.Column = [1 2];

    s.btnSavePreset = uibutton(s.corrGL, 'Text', 'Save', 'FontSize', tk.font.body, ...
        'Tooltip', 'Save current correction settings as a named preset', ...
        'ButtonPushedFcn', callbacks.onSavePreset);
    s.btnSavePreset.Layout.Row = CROW.REDO; s.btnSavePreset.Layout.Column = 3;

    s.btnDeletePreset = uibutton(s.corrGL, 'Text', char(10005), 'FontSize', tk.font.body, ...
        'Tooltip', 'Delete the selected preset', ...
        'ButtonPushedFcn', callbacks.onDeletePreset);
    s.btnDeletePreset.Layout.Row = CROW.REDO; s.btnDeletePreset.Layout.Column = 4;

    bosonPlotter.applyDefaultFont(s.corrGL, tk.font.body);
end
