function s = buildFileListPanel(parent, fig, tk, palette, callbacks)
%BUILDFILELISTPANEL  Sidebar dataset-list panel for BosonPlotter.
%
%   s = bosonPlotter.buildFileListPanel(parent, fig, tk, palette, callbacks)
%
%   Builds the left-column file-list sidebar:
%     • Add / Recent
%     • Batch Import / Batch XRD
%     • Remove Selected
%     • Filter (search field + clear)
%     • Merge / Dataset Math
%     • Move Up / Move Down
%     • Group dropdown + add/remove
%     • Shortcuts / Settings
%     • Dataset listbox (with right-click context menu)
%
%   Inputs
%     parent     uigridlayout / uipanel where the file panel goes (contentGL)
%     fig        top-level figure (parent for the listbox context menu —
%                uicontextmenu on uifigure components requires R2023b+)
%     tk         UX tokens
%     palette    struct of semantic button colors:
%                  .primary, .danger, .accent, .tool, .fg
%                  + .textMuted, .textHighlight (font colors for buttons)
%     callbacks  struct of function handles; see fields used below
%
%   Output
%     s          struct of widget handles. External callers reference
%                lbDatasets, ddGroup, ddRecent, efDatasetSearch,
%                fileListPanel, btnRemoveDS, btnMerge most often.

    arguments
        parent
        fig
        tk         struct
        palette    struct
        callbacks  struct
    end

    s.fileListPanel = uipanel(parent, 'Scrollable', 'on');
    s.fileListPanel.Layout.Row = 1; s.fileListPanel.Layout.Column = 1;

    % Stacked vertically: Add | Batch | Remove | Filter | Merge | Up/Down | Groups | Shortcuts | Settings | Listbox
    s.tbGL = uigridlayout(s.fileListPanel, [10 2], ...
        'RowHeight',    {22,22,22,22,22,22,22,22,22,'1x'}, ...
        'ColumnWidth',  {'1x','1x'}, ...
        'Padding',      tk.pad.flush, ...
        'RowSpacing',   2, ...
        'ColumnSpacing', 3);

    s.btnBrowse = uibutton(s.tbGL, 'Text', 'Add File(s)...', ...
        'ButtonPushedFcn', callbacks.onAddFiles, ...
        'BackgroundColor', palette.primary, ...
        'FontColor', palette.fg, 'FontWeight', 'bold', ...
        'Tooltip', 'Browse for one or more data files — each is added as a new dataset');
    s.btnBrowse.Layout.Row = 1; s.btnBrowse.Layout.Column = 1;

    s.ddRecent = uidropdown(s.tbGL, ...
        'Items', {'(recent)'}, 'Value', '(recent)', ...
        'FontSize', tk.font.label, ...
        'ValueChangedFcn', callbacks.onRecentFileSelected, ...
        'Tooltip', 'Open a recently loaded file');
    s.ddRecent.Layout.Row = 1; s.ddRecent.Layout.Column = 2;

    s.btnBatchImport = uibutton(s.tbGL, 'Text', 'Batch Import...', ...
        'ButtonPushedFcn', callbacks.onBatchImportDir, ...
        'BackgroundColor', palette.primary, 'FontColor', palette.fg, ...
        'Tooltip', 'Import all supported files from a directory (recursive)');
    s.btnBatchImport.Layout.Row = 2; s.btnBatchImport.Layout.Column = 1;

    s.btnBatchConvertXRD = uibutton(s.tbGL, 'Text', 'Batch XRD...', ...
        'ButtonPushedFcn', callbacks.onBatchConvertXRD, ...
        'BackgroundColor', palette.primary, 'FontColor', palette.fg, ...
        'Tooltip', 'Batch convert XRD files between formats');
    s.btnBatchConvertXRD.Layout.Row = 2; s.btnBatchConvertXRD.Layout.Column = 2;

    s.btnRemoveDS = uibutton(s.tbGL, 'Text', 'Remove Selected', ...
        'ButtonPushedFcn', callbacks.onRemoveDataset, ...
        'BackgroundColor', palette.danger, 'FontColor', palette.fg, ...
        'Tooltip', 'Remove the highlighted dataset from the list (also: right-click or press Delete)');
    s.btnRemoveDS.Layout.Row = 3; s.btnRemoveDS.Layout.Column = [1 2];

    % Row 4: filter field + ✕ clear (sub-grid so the button doesn't squeeze the field)
    searchGL = uigridlayout(s.tbGL, [1 2], ...
        'Padding', tk.pad.flush, 'ColumnSpacing', 2, ...
        'ColumnWidth', {'1x', 20});
    searchGL.Layout.Row = 4; searchGL.Layout.Column = [1 2];

    s.efDatasetSearch = uieditfield(searchGL, 'text', 'Value', '', ...
        'Placeholder', 'Filter datasets...', ...
        'Tooltip', 'Filter the dataset list by name (case-insensitive substring match)', ...
        'ValueChangedFcn', callbacks.onSearchChanged);
    s.efDatasetSearch.Layout.Column = 1;

    s.btnClearSearch = uibutton(searchGL, 'Text', char(10005), ...
        'ButtonPushedFcn', callbacks.clearDatasetSearch, ...
        'FontSize', tk.font.body, ...
        'Tooltip', 'Clear the dataset filter');
    s.btnClearSearch.Layout.Column = 2;

    s.btnMerge = uibutton(s.tbGL, 'Text', 'Merge Selected', ...
        'ButtonPushedFcn', callbacks.onMergeDatasets, ...
        'BackgroundColor', palette.accent, 'FontColor', palette.fg, ...
        'Tooltip', 'Concatenate 2+ selected datasets into a new merged dataset (sorted by X)');
    s.btnMerge.Layout.Row = 5; s.btnMerge.Layout.Column = 1;

    s.btnDatasetMath = uibutton(s.tbGL, 'Text', 'Dataset Math...', ...
        'ButtonPushedFcn', callbacks.onDatasetMath, ...
        'BackgroundColor', palette.accent, 'FontColor', palette.fg, ...
        'Tooltip', 'Create derived datasets via expressions: D1/D2, log10(D1), diff(D1), D1-D2, D1*D2');
    s.btnDatasetMath.Layout.Row = 5; s.btnDatasetMath.Layout.Column = 2;

    s.btnMoveUp = uibutton(s.tbGL, 'Text', [char(9650) ' Up'], ...
        'ButtonPushedFcn', callbacks.onMoveDatasetUp, ...
        'Tooltip', 'Move the active dataset up in the list (Ctrl+Up)');
    s.btnMoveUp.Layout.Row = 6; s.btnMoveUp.Layout.Column = 1;

    s.btnMoveDown = uibutton(s.tbGL, 'Text', [char(9660) ' Down'], ...
        'ButtonPushedFcn', callbacks.onMoveDatasetDown, ...
        'Tooltip', 'Move the active dataset down in the list (Ctrl+Down)');
    s.btnMoveDown.Layout.Row = 6; s.btnMoveDown.Layout.Column = 2;

    % Row 7: Dataset Groups — dropdown + add/remove
    grpGL = uigridlayout(s.tbGL, [1 3], ...
        'Padding', tk.pad.flush, 'ColumnSpacing', 2, ...
        'ColumnWidth', {'1x', 36, 20});
    grpGL.Layout.Row = 7; grpGL.Layout.Column = [1 2];

    s.ddGroup = uidropdown(grpGL, ...
        'Items', {'All Datasets'}, 'Value', 'All Datasets', ...
        'Editable', 'on', 'FontSize', tk.font.label, ...
        'Tooltip', ['Filter by group. Type a new name and press Enter to create. ' ...
                    'Select a group to filter the list.'], ...
        'ValueChangedFcn', callbacks.onGroupChanged);
    s.ddGroup.Layout.Column = 1;

    s.btnAddToGroup = uibutton(grpGL, 'Text', '+Grp', ...
        'ButtonPushedFcn', callbacks.onAddToGroup, ...
        'FontSize', tk.font.body, ...
        'Tooltip', 'Add selected dataset(s) to the current group');
    s.btnAddToGroup.Layout.Column = 2;

    s.btnRemoveFromGroup = uibutton(grpGL, 'Text', char(10005), ...
        'ButtonPushedFcn', callbacks.onRemoveFromGroup, ...
        'FontSize', tk.font.body, ...
        'Tooltip', 'Remove selected dataset(s) from the current group');
    s.btnRemoveFromGroup.Layout.Column = 3;

    % Animate lives on the axes toolbar (tbActions 'animate'); the
    % file-list duplicate was removed (repo-audit W2 #23).
    s.btnShortcuts = uibutton(s.tbGL, 'Text', '?  Shortcuts', ...
        'ButtonPushedFcn', callbacks.onShowShortcuts, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.textMuted, ...
        'FontSize', tk.font.label, 'Tooltip', 'Show keyboard shortcuts');
    s.btnShortcuts.Layout.Row = 8; s.btnShortcuts.Layout.Column = [1 2];

    s.btnSettings = uibutton(s.tbGL, 'Text', [char(9881) '  Settings...'], ...
        'ButtonPushedFcn', callbacks.onOpenSettings, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.textHighlight, ...
        'FontSize', tk.font.label, ...
        'Tooltip', 'Theme, plot style, and other global preferences');
    s.btnSettings.Layout.Row = 9; s.btnSettings.Layout.Column = [1 2];

    s.lbDatasets = uilistbox(s.tbGL, ...
        'Items',     {'(no files loaded — click  Add File(s)...  to begin)'}, ...
        'ItemsData', {0}, ...
        'Multiselect', 'on', ...
        'ValueChangedFcn', callbacks.onSelectDataset, ...
        'Tooltip', 'Loaded datasets — click to make active; Ctrl+click to select multiple; right-click to remove');
    s.lbDatasets.Layout.Row = 10; s.lbDatasets.Layout.Column = [1 2];

    % Right-click context menu on the listbox. uicontextmenu on uifigure
    % components requires R2023b+; guard for older releases.
    try
        s.cmDatasets = uicontextmenu(fig);
        uimenu(s.cmDatasets, 'Text', 'Remove Selected', ...
            'MenuSelectedFcn', @(~,~) callbacks.onRemoveDataset([], []));
        uimenu(s.cmDatasets, 'Text', 'Duplicate', ...
            'MenuSelectedFcn', @(~,~) callbacks.onDuplicateDataset([], []));
        uimenu(s.cmDatasets, 'Text', 'Hide / Show', ...
            'MenuSelectedFcn', @(~,~) callbacks.onToggleDatasetVisibility([], []));
        uimenu(s.cmDatasets, 'Text', 'Set as Background', ...
            'MenuSelectedFcn', @(~,~) callbacks.onSetActiveBG([], []));
        uimenu(s.cmDatasets, 'Text', 'Move Up', ...
            'MenuSelectedFcn', @(~,~) callbacks.onMoveDatasetUp([], []));
        uimenu(s.cmDatasets, 'Text', 'Move Down', ...
            'MenuSelectedFcn', @(~,~) callbacks.onMoveDatasetDown([], []));
        uimenu(s.cmDatasets, 'Text', 'Notes...', 'Separator', 'on', ...
            'MenuSelectedFcn', @(~,~) callbacks.onDatasetNotes());
        uimenu(s.cmDatasets, 'Text', 'Rename...', ...
            'MenuSelectedFcn', @(~,~) callbacks.onDatasetRename());
        uimenu(s.cmDatasets, 'Text', 'Reload from Disk', ...
            'MenuSelectedFcn', @(~,~) callbacks.onDatasetReload());
        uimenu(s.cmDatasets, 'Text', 'Edit Column Mapping...', 'Separator', 'on', ...
            'MenuSelectedFcn', @(~,~) callbacks.onEditColumnMapping());
        uimenu(s.cmDatasets, 'Text', 'Save as Template...', ...
            'MenuSelectedFcn', @(~,~) callbacks.onSaveAsTemplate());
        s.lbDatasets.ContextMenu = s.cmDatasets;
    catch
        % R2022a/R2022b: uicontextmenu not supported on uifigure — skip silently.
        % Users can still use toolbar buttons for these operations.
        s.cmDatasets = [];
    end
end
