function w = buildPeakWindow(appData, constants)
%BUILDPEAKWINDOW  Construct the Peak Workshop floating window.
%
%   Syntax
%     w = bosonPlotter.buildPeakWindow(appData, constants)
%
%   Inputs
%     appData   - bosonPlotter.AppState handle (provides fitCurveColor,
%                 kFactor, instBroadening_deg, peakSNR, peakProminence)
%     constants - struct with fields:
%                   .BTN_ACCENT    [1x3] RGB
%                   .BTN_EXPORT    [1x3] RGB
%                   .BTN_SECONDARY [1x3] RGB
%                   .BTN_FG        [1x3] RGB
%                   .XRAY_SOURCES  {Nx2} cell: {display-name, wavelength_A}
%
%   Outputs
%     w - struct of widget handles (all callbacks left empty; caller wires).
%         New fields vs. legacy layout: efNoise, efProminence.
%         All previously-returned fields preserved so caller wiring is
%         unchanged.
%
%   Layout
%     820x680 uifigure with three rows:
%       Row 1  — header strip (stage labels: ① Detect ② Fit ③ Analyze ④ Export)
%       Row 2  — two-column body: sidebar (Detection + XRD physics) | main pane
%                                 (peak table, fit model, fit/clear, display,
%                                  analysis tools, export)
%       Row 3  — help text

% ════════════════════════════════════════════════════════════════════
%  Unpack constants
% ════════════════════════════════════════════════════════════════════
BTN_ACCENT    = constants.BTN_ACCENT;
BTN_EXPORT    = constants.BTN_EXPORT;
BTN_SECONDARY = constants.BTN_SECONDARY;
BTN_FG        = constants.BTN_FG;
XRAY_SOURCES  = constants.XRAY_SOURCES;

tk = bosonPlotter.uxTokens(appData.theme);

% ════════════════════════════════════════════════════════════════════
%  Top-level figure (hidden until user opens Peak Workshop)
% ════════════════════════════════════════════════════════════════════
peakFig = uifigure('Name', 'Peak Workshop', 'Visible', 'off', ...
    'Position', [180 130 820 680]);

peakRootGL = uigridlayout(peakFig, [3 1], ...
    'RowHeight', {26, '1x', 22}, ...
    'Padding', [6 6 6 6], 'RowSpacing', 6);

% ════════════════════════════════════════════════════════════════════
%  Row 1 — Stage header strip
% ════════════════════════════════════════════════════════════════════
hdrGL = uigridlayout(peakRootGL, [1 5], ...
    'ColumnWidth', {'1x','1x','1x','1x', 80}, ...
    'Padding', [0 0 0 0], 'ColumnSpacing', 4);
hdrGL.Layout.Row = 1;

stageStyle = {'FontWeight','bold','FontSize',tk.font.label, ...
              'FontColor',tk.color.textMuted, ...
              'HorizontalAlignment','center'};
uilabel(hdrGL, 'Text', [char(9312) ' Detect'],  stageStyle{:});
uilabel(hdrGL, 'Text', [char(9313) ' Fit'],     stageStyle{:});
uilabel(hdrGL, 'Text', [char(9314) ' Analyze'], stageStyle{:});
uilabel(hdrGL, 'Text', [char(9315) ' Export'],  stageStyle{:});
% Reserved col 5 for future "Help" button or workflow indicator.
uilabel(hdrGL, 'Text', '');

% ════════════════════════════════════════════════════════════════════
%  Row 2 — Body: sidebar (220px) | main pane
% ════════════════════════════════════════════════════════════════════
bodyGL = uigridlayout(peakRootGL, [1 2], ...
    'ColumnWidth', {220, '1x'}, ...
    'Padding', [0 0 0 0], 'ColumnSpacing', 8);
bodyGL.Layout.Row = 2;

% ── Sidebar ───────────────────────────────────────────────────────────
sidePanel = uipanel(bodyGL, 'BorderType', 'line');
sidePanel.Layout.Column = 1;
sideGL = uigridlayout(sidePanel, [12 2], ...
    'RowHeight',   {16, 22, 22, 22, 8, ...      % Detection: hdr + 3 fields + spacer
                    16, 22, 22, 22, 22, 8, ...  % XRD physics: hdr + 4 fields + spacer
                    '1x'}, ...                  % flex filler
    'ColumnWidth', {72, '1x'}, ...
    'Padding', [8 6 8 6], 'RowSpacing', 3, 'ColumnSpacing', 4);

hdrStyle = {'FontWeight','bold','FontSize',tk.font.caption, ...
            'FontColor', tk.color.textMuted};
lblStyle = {'FontSize', tk.font.caption, 'HorizontalAlignment','right'};

% — Detection group —
hd1 = uilabel(sideGL, 'Text', 'DETECTION', hdrStyle{:});
hd1.Layout.Row = 1; hd1.Layout.Column = [1 2];

uilabel(sideGL, 'Text', 'Min sep (°):', lblStyle{:}, ...
    'Tooltip','Minimum peak separation in x-units. 0 = automatic (~1% of x-range).');
efMinSep = uispinner(sideGL, ...
    'Value', 0, 'Limits', [0 20], 'Step', 0.05, ...
    'ValueDisplayFormat', '%.2f', ...
    'Tooltip', ['Minimum peak separation for auto-detect.  ' ...
                '0 = automatic (~1% of x-range).  ' ...
                'Decrease to resolve closely-spaced peaks.']);

uilabel(sideGL, 'Text', 'Noise (SNR):', lblStyle{:}, ...
    'Tooltip','Signal-to-noise ratio threshold. Lower = more peaks detected.');
efNoise = uispinner(sideGL, ...
    'Value', appData.peakSNR, ...
    'Limits', [0.5 50], 'Step', 0.5, ...
    'ValueDisplayFormat', '%.1f', ...
    'Tooltip', ['SNR threshold for peak detection.  ' ...
                'Lower (e.g. 3) finds more peaks; higher (e.g. 8) is stricter.  ' ...
                'Default 5 is a balanced setting.']);

uilabel(sideGL, 'Text', 'Min prom:', lblStyle{:}, ...
    'Tooltip','Minimum peak prominence (fraction of y-range). Lower = more peaks.');
efProminence = uispinner(sideGL, ...
    'Value', appData.peakProminence, ...
    'Limits', [0 1], 'Step', 0.005, ...
    'ValueDisplayFormat', '%.3f', ...
    'Tooltip', ['Minimum prominence as a fraction of y-range.  ' ...
                'Default 0.02 (2%).  Lower for subtle peaks; raise to filter noise.']);

% — XRD physics group —
hd2 = uilabel(sideGL, 'Text', 'XRD PHYSICS', hdrStyle{:});
hd2.Layout.Row = 6; hd2.Layout.Column = [1 2];

uilabel(sideGL, 'Text', 'X-ray src:', lblStyle{:}, ...
    'Tooltip','Pick a source to auto-fill wavelength.');
ddXraySource = uidropdown(sideGL, ...
    'Items',   XRAY_SOURCES(:,1)', ...
    'Value',   XRAY_SOURCES{1,1}, ...
    'FontSize', tk.font.caption, ...
    'Tooltip', 'Select X-ray source to auto-fill wavelength; pick Custom to type manually.');

uilabel(sideGL, 'Text', [char(955) ' (' char(197) '):'], lblStyle{:}, ...
    'Tooltip','X-ray wavelength in Ångströms.');
efWavelength = uieditfield(sideGL, 'numeric', ...
    'Value', 0, 'Limits', [0 Inf], ...
    'Tooltip', ['Wavelength in Å for d-spacing & Scherrer.  ' ...
                'Auto-filled from file metadata when available.  ' ...
                'Cu K' char(945) '1 = 1.5406 Å.  0 = not set.']);

uilabel(sideGL, 'Text', 'K factor:', lblStyle{:}, ...
    'Tooltip','Scherrer shape factor K — 0.9 (spherical) or 1.0 (cubic).');
efKFactor = uieditfield(sideGL, 'numeric', ...
    'Value', appData.kFactor, 'Limits', [0.1 2], ...
    'Tooltip', 'Scherrer shape factor K — 0.9 (spherical) or 1.0 (cubic). Affects Size (nm) column.');

uilabel(sideGL, 'Text', ['Inst ' char(946) ':'], lblStyle{:}, ...
    'Tooltip','Instrument broadening FWHM (°).');
efInstBroadening = uieditfield(sideGL, 'numeric', ...
    'Value', appData.instBroadening_deg, 'Limits', [0 5], ...
    'Tooltip', ['Instrument broadening FWHM (°). Enter the FWHM of a standard (e.g. LaB6) peak.  ' ...
                '0 = no correction applied.']);

% ── Main pane ─────────────────────────────────────────────────────────
mainPanel = uipanel(bodyGL, 'BorderType', 'none');
mainPanel.Layout.Column = 2;

% Rows: table (1x flex) | model | fit-row | display-row | analysis-row | export-row
peakBtnGL = uigridlayout(mainPanel, [6 4], ...
    'RowHeight',   {'1x', 26, 26, 24, 26, 26}, ...
    'ColumnWidth', {'1x','1x','1x','1x'}, ...
    'Padding', [0 0 0 0], 'RowSpacing', 4, 'ColumnSpacing', 4);

% Row 1 — Peak table (spans all 4 columns)
peakTable = uitable(peakBtnGL, ...
    'ColumnName',     {'#','Center (°)','d (Å)','Size (nm)','FWHM (°)','Height','Area',char(951),'Status'}, ...
    'ColumnWidth',    {22, 82, 70, 70, 68, 65, 65, 38, 55}, ...
    'Data',           {}, ...
    'RowName',        {}, ...
    'ColumnEditable', [false false false false false false false false false], ...
    'Tooltip','Detected peaks — select a row to highlight it on the plot');
peakTable.Layout.Row = 1; peakTable.Layout.Column = [1 4];

% Row 2 — Fit model (label col 1, dropdown col 2-3) | Show BG col 4
lblModel = uilabel(peakBtnGL, 'Text', 'Fit model:', ...
    'FontSize', tk.font.body, 'HorizontalAlignment', 'right');
lblModel.Layout.Row = 2; lblModel.Layout.Column = 1;

ddFitModel = uidropdown(peakBtnGL, ...
    'Items',   {'Lorentzian', 'Gaussian', 'Pseudo-Voigt', 'Split Pearson VII', 'TCH-pV'}, ...
    'Value',   'Lorentzian', ...
    'Tooltip', ['Peak shape model: Lorentzian, Gaussian, Pseudo-Voigt (' char(951) char(183) ...
                'L + (1-' char(951) ')' char(183) 'G), Split Pearson VII (asymmetric), ' ...
                'or TCH-pV (Thompson-Cox-Hastings, Rietveld-style)']);
ddFitModel.Layout.Row = 2; ddFitModel.Layout.Column = [2 3];

chkShowBG = uicheckbox(peakBtnGL, ...
    'Text',    'Show BG', ...
    'Value',   true, ...
    'FontSize', tk.font.body, ...
    'Tooltip',  'Overlay the estimated SNIP background curve on the plot');
chkShowBG.Layout.Row = 2; chkShowBG.Layout.Column = 4;

% Row 3 — Fit Peaks | Fit All | Clear All | Remove Sel.
btnFitPeaks = uibutton(peakBtnGL,'Text','Fit Peaks', ...
    'BackgroundColor',BTN_ACCENT,'FontColor',BTN_FG, ...
    'Tooltip','Fit the selected model to each listed peak and extract precise center and FWHM');
btnFitPeaks.Layout.Row = 3; btnFitPeaks.Layout.Column = 1;

btnFitAllPeaks = uibutton(peakBtnGL,'Text','Fit All (global)', ...
    'BackgroundColor',BTN_ACCENT,'FontColor',BTN_FG, ...
    'Tooltip','Fit all peaks simultaneously as a single multi-peak model (requires ≥2 peaks)');
btnFitAllPeaks.Layout.Row = 3; btnFitAllPeaks.Layout.Column = 2;

btnClearPeaks = uibutton(peakBtnGL,'Text','Clear All', ...
    'Tooltip','Remove all peaks for the active dataset');
btnClearPeaks.Layout.Row = 3; btnClearPeaks.Layout.Column = 3;

btnRemovePeak = uibutton(peakBtnGL,'Text','Remove Sel.', ...
    'Tooltip','Remove the currently highlighted peak from the list');
btnRemovePeak.Layout.Row = 3; btnRemovePeak.Layout.Column = 4;

% Row 4 — Display: Show fit curves | Fit color... | Fringe Δt | (reserved)
chkShowFit = uicheckbox(peakBtnGL, ...
    'Text',    'Show fit curves', ...
    'Value',   true, ...
    'FontSize', tk.font.body, ...
    'Tooltip',  'Overlay fit curves on the plot');
chkShowFit.Layout.Row = 4; chkShowFit.Layout.Column = 1;

btnFitColor = uibutton(peakBtnGL, 'Text', 'Fit color', ...
    'FontSize', tk.font.body, ...
    'Tooltip', 'Pick the color used for fit curve overlays');
btnFitColor.Layout.Row = 4; btnFitColor.Layout.Column = 2;
btnFitColor.BackgroundColor = appData.fitCurveColor;

btnFringeThick = uibutton(peakBtnGL, 'Text', ['Fringe ' char(916) 't (2-click)'], ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'FontSize', tk.font.caption, ...
    'Tooltip', ['Pick two fringe peaks to estimate film thickness via t = 2' char(960) ...
                '/' char(916) 'Q.  Points are draggable for refinement.']);
btnFringeThick.Layout.Row = 4; btnFringeThick.Layout.Column = [3 4];
btnFringeThick.Visible = 'off';  % shown only for reflectometry data

% Row 5 — Analysis: W-H Plot | FFT Thick. | Lattice... | Match Phases
btnWHPlot = uibutton(peakBtnGL, 'Text', 'W-H Plot', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', ['Williamson-Hall strain analysis: plot ' char(946) char(183) ...
                'cos' char(952) ' vs 4' char(183) 'sin' char(952) ...
                '.  Needs ' char(8805) '3 fitted peaks.']);
btnWHPlot.Layout.Row = 5; btnWHPlot.Layout.Column = 1;

btnFFTThickness = uibutton(peakBtnGL, 'Text', 'FFT Thick.', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', 'Compute film thickness from Laue / Kiessig fringe periodicity via FFT');
btnFFTThickness.Layout.Row = 5; btnFFTThickness.Layout.Column = 2;

btnRefineLattice = uibutton(peakBtnGL, 'Text', 'Lattice', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', 'Refine lattice parameters from fitted peak positions + hkl Miller indices');
btnRefineLattice.Layout.Row = 5; btnRefineLattice.Layout.Column = 3;

btnMatchPhases = uibutton(peakBtnGL, 'Text', 'Match Phases', ...
    'BackgroundColor', [0.20 0.50 0.35], 'FontColor', BTN_FG, ...
    'Tooltip', ['Match detected peak d-spacings against a built-in database of ~50 phases ' ...
                '(metals, oxides, substrates, perovskites). Tolerance slider adjustable.']);
btnMatchPhases.Layout.Row = 5; btnMatchPhases.Layout.Column = 4;

% Row 6 — Export: CSV | XLSX | Copy | Refl. FFT
btnSavePeaks = uibutton(peakBtnGL,'Text','Export CSV', ...
    'BackgroundColor',BTN_EXPORT,'FontColor',BTN_FG, ...
    'Tooltip','Save peak centers and FWHM values to a CSV file');
btnSavePeaks.Layout.Row = 6; btnSavePeaks.Layout.Column = 1;

btnExportPeakXLSX = uibutton(peakBtnGL,'Text','Export XLSX', ...
    'BackgroundColor',BTN_EXPORT,'FontColor',BTN_FG, ...
    'Tooltip','Export peak data from all datasets to an Excel file (.xlsx)');
btnExportPeakXLSX.Layout.Row = 6; btnExportPeakXLSX.Layout.Column = 2;

btnCopyPeaksClip = uibutton(peakBtnGL,'Text','Copy Peaks', ...
    'BackgroundColor', BTN_SECONDARY, 'FontColor', BTN_FG, ...
    'Tooltip', 'Copy peak table as tab-delimited text to clipboard');
btnCopyPeaksClip.Layout.Row = 6; btnCopyPeaksClip.Layout.Column = 3;

btnReflFFT = uibutton(peakBtnGL, 'Text', 'Refl. FFT', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', ['Compute film thickness from Kiessig fringes via FFT.' newline ...
                'For neutron/XRR data (Q-space). Also works for XRD in 2' char(952) ...
                '-space if wavelength is set.']);
btnReflFFT.Layout.Row = 6; btnReflFFT.Layout.Column = 4;

% ════════════════════════════════════════════════════════════════════
%  Row 3 — Help text
% ════════════════════════════════════════════════════════════════════
lblPeakHelp = uilabel(peakRootGL, ...
    'Text', ['Auto-detect from main window, or use Add Peak (manual click).  ' ...
             'Tune Detection params at left, then choose model and Fit.  ' ...
             'Close this window to hide; peaks stay on plot.'], ...
    'FontSize', tk.font.caption, 'FontColor', tk.color.textMuted, ...
    'HorizontalAlignment', 'center');
lblPeakHelp.Layout.Row = 3;

% ════════════════════════════════════════════════════════════════════
%  Legacy widgets retained for back-compat with caller wiring code.
%  The "Advanced..." collapse + per-action sub-buttons no longer exist
%  in the new layout; instead btnMorePeak is provided as a hidden
%  no-op handle so the wire-up in BosonPlotter.m doesn't blow up.
%  When the caller is updated, remove btnMorePeak entirely.
% ════════════════════════════════════════════════════════════════════
btnMorePeak = uibutton(peakBtnGL, 'Text', '', 'Visible', 'off');
btnMorePeak.Layout.Row = 6; btnMorePeak.Layout.Column = 4;  % overlapped; hidden

% ════════════════════════════════════════════════════════════════════
%  Pack output struct (preserves legacy field set; adds efNoise + efProminence)
% ════════════════════════════════════════════════════════════════════
w.peakFig           = peakFig;
w.peakBtnGL         = peakBtnGL;
w.peakTable         = peakTable;
w.ddFitModel        = ddFitModel;
w.btnFitPeaks       = btnFitPeaks;
w.btnFitAllPeaks    = btnFitAllPeaks;
w.btnClearPeaks     = btnClearPeaks;
w.btnRemovePeak     = btnRemovePeak;
w.btnSavePeaks      = btnSavePeaks;
w.btnExportPeakXLSX = btnExportPeakXLSX;
w.btnCopyPeaksClip  = btnCopyPeaksClip;
w.btnFitColor       = btnFitColor;
w.chkShowFit        = chkShowFit;
w.btnReflFFT        = btnReflFFT;
w.btnFringeThick    = btnFringeThick;
w.btnMorePeak       = btnMorePeak;          % legacy no-op
w.btnWHPlot         = btnWHPlot;
w.btnFFTThickness   = btnFFTThickness;
w.btnRefineLattice  = btnRefineLattice;
w.btnMatchPhases    = btnMatchPhases;
w.efMinSep          = efMinSep;
w.efNoise           = efNoise;              % NEW
w.efProminence      = efProminence;         % NEW
w.efWavelength      = efWavelength;
w.efKFactor         = efKFactor;
w.efInstBroadening  = efInstBroadening;
w.ddXraySource      = ddXraySource;
w.chkShowBG         = chkShowBG;
w.XRAY_SOURCES      = XRAY_SOURCES;

end
