function w = buildPeakWindow(appData, constants)
%BUILDPEAKWINDOW  Construct the Peak Analysis floating window.
%
%   Syntax
%     w = bosonPlotter.buildPeakWindow(appData, constants)
%
%   Inputs
%     appData   - bosonPlotter.AppState handle object (provides fitCurveColor,
%                 kFactor, instBroadening_deg)
%     constants - struct with fields:
%                   .BTN_ACCENT    [1x3] RGB
%                   .BTN_EXPORT    [1x3] RGB
%                   .BTN_SECONDARY [1x3] RGB
%                   .BTN_FG        [1x3] RGB
%                   .XRAY_SOURCES  {Nx2} cell: {display-name, wavelength_A}
%
%   Outputs
%     w - struct of widget handles (all callbacks left empty; caller wires them)
%
%       w.peakFig            uifigure  (Visible='off')
%       w.peakBtnGL          uigridlayout  (needed by onToggleAdvancedPeakTools)
%       w.peakTable          uitable
%       w.ddFitModel         uidropdown
%       w.btnFitPeaks        uibutton
%       w.btnFitAllPeaks     uibutton
%       w.btnClearPeaks      uibutton
%       w.btnRemovePeak      uibutton
%       w.btnSavePeaks       uibutton
%       w.btnExportPeakXLSX  uibutton
%       w.btnCopyPeaksClip   uibutton
%       w.btnFitColor        uibutton  (BackgroundColor pre-set from appData)
%       w.chkShowFit         uicheckbox
%       w.btnReflFFT         uibutton
%       w.btnFringeThick     uibutton  (Visible='off')
%       w.btnMorePeak        uibutton
%       w.btnWHPlot          uibutton
%       w.btnFFTThickness    uibutton
%       w.btnRefineLattice   uibutton
%       w.btnMatchPhases     uibutton
%       w.efMinSep           uispinner
%       w.efWavelength       uieditfield (numeric)
%       w.efKFactor          uieditfield (numeric)
%       w.efInstBroadening   uieditfield (numeric)
%       w.ddXraySource       uidropdown
%       w.chkShowBG          uicheckbox
%       w.XRAY_SOURCES       {Nx2} cell (passed through for caller use)
%
%   Examples
%     c = struct('BTN_ACCENT',[0.15 0.37 0.63],'BTN_EXPORT',[0.18 0.32 0.52], ...
%                'BTN_SECONDARY',[0.25 0.28 0.35],'BTN_FG',[1 1 1], ...
%                'XRAY_SOURCES', {XRAY_SOURCES});
%     w = bosonPlotter.buildPeakWindow(appData, c);
%     w.peakFig.CloseRequestFcn = @(~,~) set(w.peakFig,'Visible','off');
%     w.peakTable.CellSelectionCallback = @onPeakTableSelect;
%     % ... wire remaining callbacks ...

% ════════════════════════════════════════════════════════════════════
%  Unpack constants
% ════════════════════════════════════════════════════════════════════
BTN_ACCENT    = constants.BTN_ACCENT;
BTN_EXPORT    = constants.BTN_EXPORT;
BTN_SECONDARY = constants.BTN_SECONDARY;
BTN_FG        = constants.BTN_FG;
XRAY_SOURCES  = constants.XRAY_SOURCES;

% ════════════════════════════════════════════════════════════════════
%  Top-level figure (hidden until user opens Peak Analysis)
% ════════════════════════════════════════════════════════════════════
peakFig = uifigure('Name', 'Peak Analysis', 'Visible', 'off', ...
    'Position', [200 150 580 620]);
% CloseRequestFcn needs peakFig in scope — caller sets it after receiving w.

peakRootGL = uigridlayout(peakFig, [3 1], ...
    'RowHeight', {'1x', 340, 24}, ...
    'Padding', [6 6 6 6], 'RowSpacing', 4);

% ════════════════════════════════════════════════════════════════════
%  Row 1: Peak data table
% ════════════════════════════════════════════════════════════════════
peakTable = uitable(peakRootGL, ...
    'ColumnName',     {'#','Center (°)','d (Å)','Size (nm)','FWHM (°)','Height','Area',char(951),'Status'}, ...
    'ColumnWidth',    {22, 82, 70, 70, 68, 65, 65, 38, 55}, ...
    'Data',           {}, ...
    'RowName',        {}, ...
    'ColumnEditable', [false false false false false false false false false], ...
    'Tooltip','Detected peaks — select a row to highlight it on the plot');
peakTable.Layout.Row = 1;

% ════════════════════════════════════════════════════════════════════
%  Row 2: Button grid (10 rows × 2 cols)
% ════════════════════════════════════════════════════════════════════
peakBtnGL = uigridlayout(peakRootGL, [10 2], ...
    'RowHeight',    {24,22,22,22,22,22,0, 18, 0, 96}, ...
    'ColumnWidth',  {'1x','1x'}, ...
    'Padding',      [0 0 0 0], ...
    'RowSpacing',   2, ...
    'ColumnSpacing', 4);
peakBtnGL.Layout.Row = 2;

% Row 1: Fit model dropdown (spans both columns)
ddFitModel = uidropdown(peakBtnGL, ...
    'Items',   {'Lorentzian', 'Gaussian', 'Pseudo-Voigt', 'Split Pearson VII'}, ...
    'Value',   'Lorentzian', ...
    'Tooltip', ['Peak shape model: Lorentzian, Gaussian, Pseudo-Voigt (' char(951) char(183) ...
                'L + (1-' char(951) ')' char(183) 'G), or Split Pearson VII (asymmetric)']);
ddFitModel.Layout.Row = 1; ddFitModel.Layout.Column = [1 2];

% Row 2: Fit Peaks | Fit All
btnFitPeaks = uibutton(peakBtnGL,'Text','Fit Peaks', ...
    'BackgroundColor',BTN_ACCENT,'FontColor',BTN_FG, ...
    'Tooltip','Fit the selected model to each listed peak and extract precise center and FWHM');
btnFitPeaks.Layout.Row = 2; btnFitPeaks.Layout.Column = 1;

btnFitAllPeaks = uibutton(peakBtnGL,'Text','Fit All (global)', ...
    'BackgroundColor',BTN_ACCENT,'FontColor',BTN_FG, ...
    'Tooltip','Fit all peaks simultaneously as a single multi-peak model (requires ≥2 peaks)');
btnFitAllPeaks.Layout.Row = 2; btnFitAllPeaks.Layout.Column = 2;

% Row 3: Clear All | Remove Selected
btnClearPeaks = uibutton(peakBtnGL,'Text','Clear All', ...
    'Tooltip','Remove all peaks for the active dataset');
btnClearPeaks.Layout.Row = 3; btnClearPeaks.Layout.Column = 1;

btnRemovePeak = uibutton(peakBtnGL,'Text','Remove Sel.', ...
    'Tooltip','Remove the currently highlighted peak from the list');
btnRemovePeak.Layout.Row = 3; btnRemovePeak.Layout.Column = 2;

% Row 4: Export CSV | Export XLSX
btnSavePeaks = uibutton(peakBtnGL,'Text','Export CSV', ...
    'BackgroundColor',BTN_EXPORT,'FontColor',BTN_FG, ...
    'Tooltip','Save peak centers and FWHM values to a CSV file');
btnSavePeaks.Layout.Row = 4; btnSavePeaks.Layout.Column = 1;

btnExportPeakXLSX = uibutton(peakBtnGL,'Text','Export XLSX', ...
    'BackgroundColor',BTN_EXPORT,'FontColor',BTN_FG, ...
    'Tooltip','Export peak data from all datasets to an Excel file (.xlsx)');
btnExportPeakXLSX.Layout.Row = 4; btnExportPeakXLSX.Layout.Column = 2;

% Row 5: Copy Peaks | Fit Color
btnCopyPeaksClip = uibutton(peakBtnGL,'Text','Copy Peaks', ...
    'BackgroundColor', BTN_SECONDARY, 'FontColor', BTN_FG, ...
    'Tooltip', 'Copy peak table as tab-delimited text to clipboard');
btnCopyPeaksClip.Layout.Row = 5; btnCopyPeaksClip.Layout.Column = 1;

btnFitColor = uibutton(peakBtnGL, 'Text', 'Fit color...', ...
    'Tooltip', 'Pick the color used for fit curve overlays');
btnFitColor.Layout.Row = 5; btnFitColor.Layout.Column = 2;
btnFitColor.BackgroundColor = appData.fitCurveColor;

% Row 6: Show fit curves | Reflectivity FFT
chkShowFit = uicheckbox(peakBtnGL, ...
    'Text',    'Show fit curves', ...
    'Value',   true, ...
    'Tooltip',  'Overlay fit curves on the plot');
chkShowFit.Layout.Row = 6; chkShowFit.Layout.Column = 1;

btnReflFFT = uibutton(peakBtnGL, 'Text', 'Refl. FFT', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', ['Compute film thickness from Kiessig fringes via FFT.' newline ...
                'For neutron/XRR data (Q-space). Also works for XRD in 2' char(952) ...
                '-space if wavelength is set.']);
btnReflFFT.Layout.Row = 6; btnReflFFT.Layout.Column = 2;

% Row 7: Fringe thickness (2-click) — visible only in reflectometry mode
btnFringeThick = uibutton(peakBtnGL, 'Text', ['Fringe ' char(916) 't (2-click)'], ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'FontSize', 9, ...
    'Tooltip', ['Pick two fringe peaks to estimate film thickness via t = 2' char(960) ...
                '/' char(916) 'Q.  Points are draggable for refinement.']);
btnFringeThick.Layout.Row = 7; btnFringeThick.Layout.Column = [1 2];
btnFringeThick.Visible = 'off';  % shown only for reflectometry data

% Row 8: "Advanced..." toggle (collapsed by default)
PEAK_ADV_ROWS    = 9;    %#ok<NASGU> — referenced by caller via naming convention
PEAK_ADV_HEIGHTS = 46;   %#ok<NASGU>
btnMorePeak = uibutton(peakBtnGL, 'Text', [char(9654) ' Advanced...'], ...
    'FontSize', 9, 'FontColor', [0.55 0.55 0.55], ...
    'BackgroundColor', peakBtnGL.BackgroundColor, ...
    'HorizontalAlignment', 'left');
btnMorePeak.Layout.Row = 8; btnMorePeak.Layout.Column = [1 2];

% Row 9: Advanced peak tools (collapsed by default) — 2×3 sub-grid
peakAdvGL = uigridlayout(peakBtnGL, [2 3], ...
    'Padding', [0 0 0 0], 'ColumnSpacing', 3, 'RowSpacing', 2, ...
    'ColumnWidth', {'1x','1x','1x'}, 'RowHeight', {22, 22});
peakAdvGL.Layout.Row = 9; peakAdvGL.Layout.Column = [1 2];

btnWHPlot = uibutton(peakAdvGL, 'Text', 'W-H Plot', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', ['Williamson-Hall strain analysis: plot ' char(946) char(183) ...
                'cos' char(952) ' vs 4' char(183) 'sin' char(952) ...
                '.  Needs ' char(8805) '3 fitted peaks.']);
btnWHPlot.Layout.Row = 1; btnWHPlot.Layout.Column = 1;

btnFFTThickness = uibutton(peakAdvGL, 'Text', 'FFT Thick.', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', 'Compute film thickness from Laue / Kiessig fringe periodicity via FFT');
btnFFTThickness.Layout.Row = 1; btnFFTThickness.Layout.Column = 2;

btnRefineLattice = uibutton(peakAdvGL, 'Text', 'Lattice...', ...
    'BackgroundColor', BTN_ACCENT, 'FontColor', BTN_FG, ...
    'Tooltip', 'Refine lattice parameters from fitted peak positions + hkl Miller indices');
btnRefineLattice.Layout.Row = 1; btnRefineLattice.Layout.Column = 3;

btnMatchPhases = uibutton(peakAdvGL, 'Text', 'Match Phases', ...
    'BackgroundColor', [0.20 0.50 0.35], 'FontColor', BTN_FG, ...
    'Tooltip', ['Match detected peak d-spacings against a built-in database of ~50 phases ' ...
                '(metals, oxides, substrates, perovskites). Tolerance slider adjustable.']);
btnMatchPhases.Layout.Row = 2; btnMatchPhases.Layout.Column = [1 3];

% ════════════════════════════════════════════════════════════════════
%  Row 10: Settings sub-grid (min sep, wavelength, K factor, inst. broadening)
% ════════════════════════════════════════════════════════════════════
minSepGL = uigridlayout(peakBtnGL, [4 4], ...
    'RowHeight', {22,22,24,20}, 'ColumnWidth', {50, '1x', 50, '1x'}, ...
    'Padding', [0 0 0 0], 'ColumnSpacing', 3, 'RowSpacing', 2);
minSepGL.Layout.Row = 10; minSepGL.Layout.Column = [1 2];

% Row 1: Min sep | Wavelength
lblMinSep = uilabel(minSepGL, 'Text', 'Min sep:', 'FontSize', 9, ...
    'HorizontalAlignment', 'right', ...
    'Tooltip', 'Minimum peak separation in degrees');
lblMinSep.Layout.Row = 1; lblMinSep.Layout.Column = 1;
efMinSep = uispinner(minSepGL, ...
    'Value', 0, 'Limits', [0 20], 'Step', 0.05, ...
    'Tooltip', ['Minimum peak separation (°) for auto-detect.  ' ...
                '0 = automatic (~1% of x-range).  ' ...
                'Decrease to resolve closely-spaced peaks.'], ...
    'ValueDisplayFormat', '%.2f');
efMinSep.Layout.Row = 1; efMinSep.Layout.Column = 2;

lblWavelength = uilabel(minSepGL, 'Text', [char(955), ' (', char(197), '):'], 'FontSize', 9, ...
    'HorizontalAlignment', 'right', ...
    'Tooltip', 'X-ray wavelength in Ångströms for d-spacing / Scherrer calculations');
lblWavelength.Layout.Row = 1; lblWavelength.Layout.Column = 3;
efWavelength = uieditfield(minSepGL, 'numeric', ...
    'Value', 0, 'Limits', [0 Inf], ...
    'Tooltip', ['Wavelength in Å for d-spacing & Scherrer.  ' ...
                'Auto-filled from file metadata when available.  ' ...
                'Cu K' char(945) '1 = 1.5406 Å.  0 = not set.']);
efWavelength.Layout.Row = 1; efWavelength.Layout.Column = 4;

% Row 2: K factor | Instrument broadening
lblKFactor = uilabel(minSepGL, 'Text', 'K:', 'FontSize', 9, ...
    'HorizontalAlignment', 'right', ...
    'Tooltip', 'Scherrer shape factor K (0.9 for spherical grains, 1.0 for cubic)');
lblKFactor.Layout.Row = 2; lblKFactor.Layout.Column = 1;
efKFactor = uieditfield(minSepGL, 'numeric', ...
    'Value', appData.kFactor, 'Limits', [0.1 2], ...
    'Tooltip', 'Scherrer shape factor K — 0.9 (spherical) or 1.0 (cubic). Affects Size (nm) column.');
efKFactor.Layout.Row = 2; efKFactor.Layout.Column = 2;

lblInstB = uilabel(minSepGL, 'Text', ['Inst ', char(946), ':'], 'FontSize', 9, ...
    'HorizontalAlignment', 'right', ...
    'Tooltip', ['Instrument broadening FWHM in degrees (e.g. LaB6 standard).  ' ...
                '0 = no correction.  Subtracted in quadrature: ' ...
                char(946), char(8321), char(8325), char(8331), ...
                ' = sqrt(', char(946), char(8322), char(8320), char(8322), char(8331), ...
                ' - ', char(946), char(8321), char(8326), char(8331), char(8322), ')']);
lblInstB.Layout.Row = 2; lblInstB.Layout.Column = 3;
efInstBroadening = uieditfield(minSepGL, 'numeric', ...
    'Value', appData.instBroadening_deg, 'Limits', [0 5], ...
    'Tooltip', ['Instrument broadening FWHM (°). Enter the FWHM of a standard (e.g. LaB6) peak.  ' ...
                '0 = no correction applied.']);
efInstBroadening.Layout.Row = 2; efInstBroadening.Layout.Column = 4;

% Row 3: X-ray source dropdown (spans all 4 columns)
ddXraySource = uidropdown(minSepGL, ...
    'Items',   XRAY_SOURCES(:,1)', ...
    'Value',   XRAY_SOURCES{1,1}, ...
    'FontSize', 9, ...
    'Tooltip', 'Select X-ray source to auto-fill wavelength; pick Custom to type manually');
ddXraySource.Layout.Row = 3; ddXraySource.Layout.Column = [1 4];

% Row 4: Show BG checkbox
chkShowBG = uicheckbox(minSepGL, ...
    'Text',    'Show BG', ...
    'Value',   true, ...
    'FontSize', 9, ...
    'Tooltip',  'Overlay the estimated SNIP background curve on the plot');
chkShowBG.Layout.Row = 4; chkShowBG.Layout.Column = [1 2];

% ════════════════════════════════════════════════════════════════════
%  Row 3 of peakRootGL: help label
% ════════════════════════════════════════════════════════════════════
lblPeakHelp = uilabel(peakRootGL, ...
    'Text', ['Select model ' char(8594) ' Fit Peaks.  Use Add Peak (main window) to click on the plot.  ' ...
             'Close this window to hide; peaks stay on plot.'], ...
    'FontSize', 9, 'FontColor', [0.55 0.55 0.55], ...
    'HorizontalAlignment', 'center');
lblPeakHelp.Layout.Row = 3;

% ════════════════════════════════════════════════════════════════════
%  Pack output struct
% ════════════════════════════════════════════════════════════════════
w.peakFig           = peakFig;
w.peakBtnGL         = peakBtnGL;
w.peakTable         = peakTable;
w.ddFitModel        = ddFitModel;
w.btnFitPeaks       = btnFitPeaks;
w.btnFitAllPeaks    = btnFitAllPeaks;
w.btnClearPeaks     = btnClearPeaks;
w.btnRemovePeak     = btnRemovePeak;
w.btnSavePeaks      = btnSavePeaks;
w.btnExportPeakXLSX = btnExportPeakXLSX;
w.btnCopyPeaksClip  = btnCopyPeaksClip;
w.btnFitColor       = btnFitColor;
w.chkShowFit        = chkShowFit;
w.btnReflFFT        = btnReflFFT;
w.btnFringeThick    = btnFringeThick;
w.btnMorePeak       = btnMorePeak;
w.btnWHPlot         = btnWHPlot;
w.btnFFTThickness   = btnFFTThickness;
w.btnRefineLattice  = btnRefineLattice;
w.btnMatchPhases    = btnMatchPhases;
w.efMinSep          = efMinSep;
w.efWavelength      = efWavelength;
w.efKFactor         = efKFactor;
w.efInstBroadening  = efInstBroadening;
w.ddXraySource      = ddXraySource;
w.chkShowBG         = chkShowBG;
w.XRAY_SOURCES      = XRAY_SOURCES;   % pass-through for caller (onXraySourceChanged needs it)

end
