function s = buildExportPanel(parent, fig, tk, palette, callbacks)
%BUILDEXPORTPANEL  Save / Export panel for BosonPlotter (analysisGL col 4).
%
%   s = bosonPlotter.buildExportPanel(parent, fig, tk, palette, callbacks)
%
%   Builds the four-section collapsible export panel:
%     ▾ Data Export   — CSV format, Save, Batch, Copy, HDF5
%     ▾ Figure Export — To Figure, Copy Plot, format dropdown, Save Figure,
%                       size width/height
%     ▸ Session       — Save / Load / Send to Origin / Origin Script
%     ▸ Tools         — Figures / Templates / Overlay / Batch Figs /
%                       Plot Options
%
%   The first two sections are open by default (Save figure is daily work
%   per audit W2 #19); Session and Tools are collapsed.
%
%   Inputs
%     parent     uigridlayout / uipanel where the panel goes (analysisGL)
%     fig        top-level figure (used to parent the hidden efSavePath
%                edit field — it lives outside the panel so callbacks can
%                read it without forcing the panel open)
%     tk         UX tokens struct (tk.font.*, tk.pad.*, tk.color.*)
%     palette    struct of semantic button colors:
%                  .export, .secondary, .session, .external, .tool, .fg
%     callbacks  struct of function handles (one per button); see fields
%                referenced below — each is wired straight into the
%                widget's ButtonPushedFcn / ValueChangedFcn.
%
%   Output
%     s          struct of widget handles + section-row metadata. Fields:
%                  .panel, .saveGL, .saveDataGL, .saveFigGL,
%                  .saveSessionGL, .saveToolsGL,
%                  .btnSaveHdrData, .btnSaveHdrFig, .btnSaveHdrSession,
%                  .btnSaveHdrTools, .efSavePath, .ddExportFormat,
%                  .btnSaveBrowse, .btnSave, .btnBatchExport,
%                  .btnCopyDataClip, .btnExportHDF5, .btnExportFig,
%                  .btnCopyClip, .ddFigFormat, .btnSaveFig, .efFigWidth,
%                  .efFigHeight, .btnSaveSession, .btnLoadSession,
%                  .btnSendOrigin, .btnExportOriginScript, .btnAdvFigure,
%                  .btnTemplates, .cbOverlayMode, .btnBatchFigExport,
%                  .btnPlotOpt2, .saveSectionRows, .saveSectionHeights.

    arguments
        parent
        fig
        tk         struct
        palette    struct
        callbacks  struct
    end

    SAVE_SEC_H = 20;    % header row height
    SAVE_ROW_H = 78;    % content block height (3 rows of 24 + spacing)

    s.panel = uipanel(parent, 'Title', 'Save / Export', ...
        'FontSize', tk.font.title, 'Scrollable', 'on');
    s.panel.Layout.Row = [1 2]; s.panel.Layout.Column = 4;

    % Vertical stacked layout with collapsible section headers
    % Rows: [hdrData, dataContent, hdrFig, figContent, hdrSession, sessionContent, hdrTools, toolsContent]
    s.saveGL = uigridlayout(s.panel, [8 1], ...
        'RowHeight', {SAVE_SEC_H, SAVE_ROW_H, SAVE_SEC_H, SAVE_ROW_H, SAVE_SEC_H, 0, SAVE_SEC_H, 0}, ...
        'ColumnWidth', {'1x'}, ...
        'Padding',     tk.pad.tight, ...
        'RowSpacing',  1);

    % Hidden path field — parented to fig (invisible), only read/written by callbacks
    s.efSavePath = uieditfield(fig, 'Value', '', 'Visible', 'off', ...
        'Placeholder', '(auto-set on dataset load or Apply)', ...
        'Tooltip', 'Output CSV file path');

    % Section row + height bookkeeping (caller assigns to appData)
    s.saveSectionRows    = struct('dataExport', 2, 'figExport', 4, 'session', 6, 'tools', 8);
    s.saveSectionHeights = struct('dataExport', SAVE_ROW_H, 'figExport', SAVE_ROW_H, ...
                                  'session', SAVE_ROW_H, 'tools', SAVE_ROW_H);

    % ── Header: Data Export (open by default) ────────────────────────
    s.btnSaveHdrData = bosonPlotter.sectionHeader(s.saveGL, [char(9660) ' Data Export'], ...
        callbacks.toggleDataExport, ...
        'FontColor', tk.color.textHighlight);
    s.btnSaveHdrData.Layout.Row = 1;

    s.saveDataGL = uigridlayout(s.saveGL, [3 2], ...
        'RowHeight', {24, 24, 24}, 'ColumnWidth', {'1x','1x'}, ...
        'Padding', tk.pad.flush, 'RowSpacing', 2, 'ColumnSpacing', 3);
    s.saveDataGL.Layout.Row = 2;

    s.ddExportFormat = uidropdown(s.saveDataGL, ...
        'Items',   {'Standard CSV', 'Origin ASCII'}, ...
        'Value',   'Standard CSV', ...
        'Tooltip', 'CSV format: Standard or Origin ASCII');
    s.ddExportFormat.Layout.Row = 1; s.ddExportFormat.Layout.Column = 1;

    s.btnSaveBrowse = uibutton(s.saveDataGL, 'Text', 'Browse', ...
        'ButtonPushedFcn', callbacks.onSaveBrowse, ...
        'Tooltip', 'Choose output file location');
    s.btnSaveBrowse.Layout.Row = 1; s.btnSaveBrowse.Layout.Column = 2;

    s.btnSave = uibutton(s.saveDataGL, 'Text', 'Save As', ...
        'ButtonPushedFcn', callbacks.onSaveCSV, ...
        'BackgroundColor', palette.export, ...
        'FontColor', palette.fg, 'FontWeight', 'bold', ...
        'Tooltip', 'Export data to CSV (Save As dialog)  [Ctrl+E]');
    s.btnSave.Layout.Row = 2; s.btnSave.Layout.Column = 1;

    s.btnBatchExport = uibutton(s.saveDataGL, 'Text', 'Batch All', ...
        'ButtonPushedFcn', callbacks.onBatchExportCSV, ...
        'BackgroundColor', palette.export, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Export all datasets to separate CSV files');
    s.btnBatchExport.Layout.Row = 2; s.btnBatchExport.Layout.Column = 2;

    s.btnCopyDataClip = uibutton(s.saveDataGL, 'Text', 'Copy Data', ...
        'ButtonPushedFcn', callbacks.onCopyDataToClipboard, ...
        'BackgroundColor', palette.export, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Copy to clipboard (tab-delimited)');
    s.btnCopyDataClip.Layout.Row = 3; s.btnCopyDataClip.Layout.Column = 1;

    s.btnExportHDF5 = uibutton(s.saveDataGL, 'Text', 'HDF5', ...
        'ButtonPushedFcn', callbacks.onExportHDF5, ...
        'BackgroundColor', palette.external, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Export to HDF5 (.h5)');
    s.btnExportHDF5.Layout.Row = 3; s.btnExportHDF5.Layout.Column = 2;

    % ── Header: Figure Export (open by default — W2 #19) ─────────────
    s.btnSaveHdrFig = bosonPlotter.sectionHeader(s.saveGL, [char(9660) ' Figure Export'], ...
        callbacks.toggleFigExport, ...
        'FontColor', tk.color.textHighlight);
    s.btnSaveHdrFig.Layout.Row = 3;

    s.saveFigGL = uigridlayout(s.saveGL, [3 2], ...
        'RowHeight', {24, 24, 24}, 'ColumnWidth', {'1x','1x'}, ...
        'Padding', tk.pad.flush, 'RowSpacing', 2, 'ColumnSpacing', 3);
    s.saveFigGL.Layout.Row = 4;

    s.btnExportFig = uibutton(s.saveFigGL, 'Text', 'To Figure', ...
        'ButtonPushedFcn', callbacks.onExportFigure, ...
        'BackgroundColor', palette.secondary, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Open in new figure window');
    s.btnExportFig.Layout.Row = 1; s.btnExportFig.Layout.Column = 1;

    s.btnCopyClip = uibutton(s.saveFigGL, 'Text', 'Copy Plot', ...
        'ButtonPushedFcn', callbacks.onCopyToClipboard, ...
        'BackgroundColor', palette.secondary, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Copy plot to clipboard [Ctrl+C]');
    s.btnCopyClip.Layout.Row = 1; s.btnCopyClip.Layout.Column = 2;

    s.ddFigFormat = uidropdown(s.saveFigGL, ...
        'Items',   {'PNG (300 dpi)', 'PDF (vector)', 'SVG (vector)', 'TIFF (300 dpi)', 'MATLAB .fig'}, ...
        'Value',   'PNG (300 dpi)', ...
        'Tooltip', 'Output format');
    s.ddFigFormat.Layout.Row = 2; s.ddFigFormat.Layout.Column = 1;

    s.btnSaveFig = uibutton(s.saveFigGL, 'Text', 'Save Figure', ...
        'ButtonPushedFcn', callbacks.onSaveFigure, ...
        'BackgroundColor', palette.secondary, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Save figure to file');
    s.btnSaveFig.Layout.Row = 2; s.btnSaveFig.Layout.Column = 2;

    figDimGL = uigridlayout(s.saveFigGL, [1 4], ...
        'Padding', tk.pad.flush, 'ColumnSpacing', 2, ...
        'ColumnWidth', {40, '1x', 12, '1x'});
    figDimGL.Layout.Row = 3; figDimGL.Layout.Column = [1 2];

    uilabel(figDimGL, 'Text', 'Size:', 'FontSize', tk.font.caption, ...
        'HorizontalAlignment', 'right');
    s.efFigWidth = uieditfield(figDimGL, 'numeric', 'Value', 7, ...
        'Limits', [1 30], 'Tooltip', 'Width (in)');
    s.efFigWidth.Layout.Column = 2;
    uilabel(figDimGL, 'Text', char(215), 'FontSize', tk.font.body, ...
        'HorizontalAlignment', 'center');
    s.efFigHeight = uieditfield(figDimGL, 'numeric', 'Value', 5, ...
        'Limits', [1 30], 'Tooltip', 'Height (in)');
    s.efFigHeight.Layout.Column = 4;

    % ── Header: Session (collapsed by default) ───────────────────────
    s.btnSaveHdrSession = bosonPlotter.sectionHeader(s.saveGL, [char(9654) ' Session'], ...
        callbacks.toggleSession, ...
        'FontColor', tk.color.textHighlight);
    s.btnSaveHdrSession.Layout.Row = 5;

    s.saveSessionGL = uigridlayout(s.saveGL, [3 2], ...
        'RowHeight', {24, 24, 24}, 'ColumnWidth', {'1x','1x'}, ...
        'Padding', tk.pad.flush, 'RowSpacing', 2, 'ColumnSpacing', 3);
    s.saveSessionGL.Layout.Row = 6;

    s.btnSaveSession = uibutton(s.saveSessionGL, 'Text', 'Save', ...
        'ButtonPushedFcn', callbacks.onSaveSession, ...
        'BackgroundColor', palette.session, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Save session (.mat) [Ctrl+S]');
    s.btnSaveSession.Layout.Row = 1; s.btnSaveSession.Layout.Column = 1;

    s.btnLoadSession = uibutton(s.saveSessionGL, 'Text', 'Load', ...
        'ButtonPushedFcn', callbacks.onLoadSession, ...
        'BackgroundColor', palette.session, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Load session (.mat)');
    s.btnLoadSession.Layout.Row = 1; s.btnLoadSession.Layout.Column = 2;

    s.btnSendOrigin = uibutton(s.saveSessionGL, 'Text', 'Send to Origin', ...
        'ButtonPushedFcn', callbacks.onSendToOrigin, ...
        'BackgroundColor', palette.external, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Send data to OriginPro via COM');
    s.btnSendOrigin.Layout.Row = 2; s.btnSendOrigin.Layout.Column = 1;

    s.btnExportOriginScript = uibutton(s.saveSessionGL, 'Text', 'Origin Script', ...
        'ButtonPushedFcn', callbacks.onExportOriginScript, ...
        'BackgroundColor', palette.external, ...
        'FontColor', palette.fg, ...
        'Tooltip', 'Write LabTalk .ogs + CSV');
    s.btnExportOriginScript.Layout.Row = 2; s.btnExportOriginScript.Layout.Column = 2;

    % ── Header: Tools (collapsed by default) ─────────────────────────
    s.btnSaveHdrTools = bosonPlotter.sectionHeader(s.saveGL, [char(9654) ' Tools'], ...
        callbacks.toggleTools, ...
        'FontColor', tk.color.textHighlight);
    s.btnSaveHdrTools.Layout.Row = 7;

    s.saveToolsGL = uigridlayout(s.saveGL, [3 2], ...
        'RowHeight', {24, 24, 24}, 'ColumnWidth', {'1x','1x'}, ...
        'Padding', tk.pad.flush, 'RowSpacing', 2, 'ColumnSpacing', 3);
    s.saveToolsGL.Layout.Row = 8;

    s.btnAdvFigure = uibutton(s.saveToolsGL, 'Text', 'Figures', ...
        'ButtonPushedFcn', callbacks.onAdvancedFigureBuilder, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, ...
        'Tooltip', 'Advanced Figure Builder');
    s.btnAdvFigure.Layout.Row = 1; s.btnAdvFigure.Layout.Column = 1;

    s.btnTemplates = uibutton(s.saveToolsGL, 'Text', 'Templates', ...
        'ButtonPushedFcn', callbacks.onPlotTemplates, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, ...
        'Tooltip', 'Save/load plot formatting presets (axis limits, corrections, labels)');
    s.btnTemplates.Layout.Row = 1; s.btnTemplates.Layout.Column = 2;

    s.cbOverlayMode = uicheckbox(s.saveToolsGL, ...
        'Text', 'Overlay', 'Value', false, ...
        'Tooltip', 'Overlay selected datasets on the same axes with unified legend', ...
        'ValueChangedFcn', callbacks.onOverlayModeChanged);
    s.cbOverlayMode.Layout.Row = 2; s.cbOverlayMode.Layout.Column = 1;

    s.btnBatchFigExport = uibutton(s.saveToolsGL, 'Text', 'Batch Figs', ...
        'ButtonPushedFcn', callbacks.onBatchFigureExport, ...
        'BackgroundColor', palette.tool, 'FontColor', palette.fg, ...
        'Tooltip', 'Export all datasets as individual figures with consistent formatting');
    s.btnBatchFigExport.Layout.Row = 2; s.btnBatchFigExport.Layout.Column = 2;

    % Row 3: Plot Options (full width). The "Advanced Analysis" button used
    % to live next to it but was removed — it duplicated the corrections
    % panel's Advanced row and confused users.
    s.btnPlotOpt2 = uibutton(s.saveToolsGL, 'Text', ['Plot Options ' char(9662)], ...
        'ButtonPushedFcn', callbacks.onShowPlotOptionsMenu, ...
        'BackgroundColor', [0.22 0.35 0.55], 'FontColor', [1 1 1], ...
        'FontWeight', 'bold', ...
        'Tooltip', 'Plot types, visualization options, and unit conversion');
    s.btnPlotOpt2.Layout.Row = 3; s.btnPlotOpt2.Layout.Column = [1 2];

    bosonPlotter.applyDefaultFont(s.saveGL, tk.font.body);
end
