function s = buildDataTablePanel(parent, fig, tk, palette, callbacks)
%BUILDDATATABLEPANEL  Data Table panel for BosonPlotter (analysisGL col 2).
%
%   s = bosonPlotter.buildDataTablePanel(parent, fig, tk, palette, callbacks)
%
%   Builds the data-table section: a toolbar row with action buttons, a
%   filter bar, a units table (1-row uitable for performance), and the
%   main editable numeric data table with a right-click context menu.
%
%   The split-table design (units table + numeric table) avoids storing
%   unit strings in the main Data matrix, which would force a cell-array
%   uitable with ~10x worse scroll performance than a pure numeric matrix.
%
%   Inputs
%     parent     uigridlayout / uipanel that contains the panel
%                (analysisGL — panel occupies rows [1 2], column 2)
%     fig        top-level uifigure (used to parent the context menu)
%     tk         UX tokens struct (tk.font.*, tk.pad.*, tk.color.*)
%     palette    struct of semantic button colors:
%                  .export   — slate colour for Save As
%                  .danger   — red for Mask Selected
%                  .primary  — green for Filter/Apply and Open DataWorkspace
%                  .tool     — theme-aware tertiary (Unmask, Stats, Sort)
%                  .fg       — button text colour
%     callbacks  struct of function handles:
%                  .onOpenDataWorkspace — opens the linked DataWorkspace window
%
%   Output
%     s          struct of widget handles. Fields:
%                  .dataTablePanel, .dataTableInnerGL,
%                  .tableBarGL, .filterBarGL,
%                  .btnTableSaveAs, .btnTableMask, .btnTableUnmask,
%                  .btnTableDescStats, .btnSortAsc, .btnSortDesc,
%                  .lblTableStats, .btnOpenDW,
%                  .lblFilter, .efFilter, .btnFilterApply, .btnFilterClear,
%                  .lblTableUnits, .tblUnits, .tblData,
%                  .miMaskRows, .miUnmaskRows, .miUnmaskAll
%
%   Usage
%     s = bosonPlotter.buildDataTablePanel(analysisGL, fig, tk, palette, cbs);
%     % Wire callbacks after tableCallbacks struct is built:
%     s.btnTableSaveAs.ButtonPushedFcn    = tblCb.onTableSaveAs;
%     s.tblData.CellEditCallback          = tblCb.onTableCellEdit;
%     % ...etc.

    arguments
        parent
        fig
        tk         struct
        palette    struct
        callbacks  struct
    end

    % ── Outer panel (analysisGL col 2, both rows) ────────────────────────
    s.dataTablePanel = uipanel(parent, 'Title', '');
    s.dataTablePanel.Layout.Row = [1 2]; s.dataTablePanel.Layout.Column = 2;

    % ── Inner grid: toolbar | filter | units label | units table | data table
    s.dataTableInnerGL = uigridlayout(s.dataTablePanel, [5 1], ...
        'RowHeight', {28, 28, 18, 26, '1x'}, 'Padding', tk.pad.tight, 'RowSpacing', 1);

    % ── Toolbar row ──────────────────────────────────────────────────────
    s.tableBarGL = uigridlayout(s.dataTableInnerGL, [1 8], ...
        'ColumnWidth', {70, 70, 55, 50, 50, 50, '1x', 100}, ...
        'RowHeight', {'1x'}, ...
        'Padding', tk.pad.barH, 'ColumnSpacing', 3);
    s.tableBarGL.Layout.Row = 1;

    s.btnTableSaveAs = uibutton(s.tableBarGL, 'Text', 'Save As', ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', palette.export, 'FontColor', palette.fg, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Save edited table to a new CSV or Excel file');
    s.btnTableSaveAs.Layout.Column = 1;

    s.btnTableMask = uibutton(s.tableBarGL, 'Text', 'Mask Sel.', ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', palette.danger, 'FontColor', palette.fg, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Mask selected rows — excluded from plot and analysis');
    s.btnTableMask.Layout.Column = 2;

    s.btnTableUnmask = uibutton(s.tableBarGL, 'Text', 'Unmask', ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', tk.color.btn.tool, 'FontColor', tk.color.text, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Remove all row masks');
    s.btnTableUnmask.Layout.Column = 3;

    s.btnTableDescStats = uibutton(s.tableBarGL, 'Text', 'Stats', ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', tk.color.btn.tool, 'FontColor', tk.color.text, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Per-column descriptive statistics');
    s.btnTableDescStats.Layout.Column = 4;

    s.btnSortAsc = uibutton(s.tableBarGL, 'Text', [char(9650) 'Asc'], ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', tk.color.btn.tool, 'FontColor', tk.color.text, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Sort by selected column (ascending)');
    s.btnSortAsc.Layout.Column = 5;

    s.btnSortDesc = uibutton(s.tableBarGL, 'Text', [char(9660) 'Desc'], ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', tk.color.btn.tool, 'FontColor', tk.color.text, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Sort by selected column (descending)');
    s.btnSortDesc.Layout.Column = 6;

    s.lblTableStats = uilabel(s.tableBarGL, 'Text', '', ...
        'FontSize', tk.font.caption, 'FontColor', tk.color.textDim, ...
        'HorizontalAlignment', 'right');
    s.lblTableStats.Layout.Column = 7;

    s.btnOpenDW = uibutton(s.tableBarGL, 'Text', [char(9783) ' Data Table'], ...
        'BackgroundColor', palette.primary, 'FontColor', palette.fg, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Open shared DataWorkspace (single instance)', ...
        'ButtonPushedFcn', callbacks.onOpenDataWorkspace);
    s.btnOpenDW.Layout.Column = 8;

    % ── Filter bar row ────────────────────────────────────────────────────
    % Layout: [label | edit field (stretch) | Filter btn | Clear btn]
    s.filterBarGL = uigridlayout(s.dataTableInnerGL, [1 4], ...
        'ColumnWidth', {30, '1x', 44, 40}, ...
        'RowHeight',   {'1x'}, ...
        'Padding', tk.pad.barH, 'ColumnSpacing', 3);
    s.filterBarGL.Layout.Row = 2;

    s.lblFilter = uilabel(s.filterBarGL, 'Text', 'Filter:', ...
        'FontSize', tk.font.caption, 'FontColor', tk.color.textMuted, ...
        'HorizontalAlignment', 'right');
    s.lblFilter.Layout.Column = 1;

    s.efFilter = uieditfield(s.filterBarGL, 'text', 'Value', '', ...
        'Placeholder', 'e.g. Temp > 300  or  between(x, 0, 1)', ...
        'FontSize', tk.font.caption, ...
        'BackgroundColor', tk.color.bgDark, 'FontColor', tk.color.text, ...
        'Tooltip', ['Filter rows by expression. Column names from labels, ' ...
                    '''x'' = X axis. Operators: > < >= <= == ~= & | ~. ' ...
                    'Functions: abs(), between(col,lo,hi). Press Enter to apply.'], ...
        'ValueChangedFcn', @(~,~) []);
    s.efFilter.Layout.Column = 2;

    s.btnFilterApply = uibutton(s.filterBarGL, 'Text', 'Filter', ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', palette.primary, 'FontColor', palette.fg, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Apply filter expression');
    s.btnFilterApply.Layout.Column = 3;

    s.btnFilterClear = uibutton(s.filterBarGL, 'Text', 'Clear', ...
        'ButtonPushedFcn', @(~,~) [], ...
        'BackgroundColor', tk.color.btn.tool, 'FontColor', tk.color.text, ...
        'FontSize', tk.font.caption, ...
        'Tooltip', 'Clear filter — show all rows');
    s.btnFilterClear.Layout.Column = 4;

    % ── Units row label (sits above the units uitable) ───────────────────
    s.lblTableUnits = uilabel(s.dataTableInnerGL, 'Text', '', ...
        'FontSize', tk.font.caption, 'FontColor', tk.color.textOk, ...
        'BackgroundColor', tk.color.bgPanel);
    s.lblTableUnits.Layout.Row = 3;

    % ── Units row (separate 1-row uitable for performance) ────────────────
    % Before the split, the main data table stored row 1 as unit strings
    % which forced the whole Data property to be a cell array.  Cell-
    % array uitables render ~10x slower than numeric matrices on scroll,
    % so we split units into their own tiny table and keep the main data
    % table pure numeric.  Column widths are kept in sync via an explicit
    % ColumnWidth array set on both tables.
    s.tblUnits = uitable(s.dataTableInnerGL, ...
        'Tag', 'BosonUnitsTable', ...
        'ColumnName', {'(no data)'}, ...
        'Data', {}, ...
        'ColumnEditable', true, ...
        'RowName', {'units'}, ...
        'CellEditCallback', @(~,~) [], ...
        'CellSelectionCallback', @(~,~) [], ...
        'FontSize', tk.font.body, ...
        'BackgroundColor', tk.color.bgInput, ...
        'ForegroundColor', tk.color.textOk);
    s.tblUnits.Layout.Row = 4;

    % ── Column context menu (right-click units row for column operations) ─
    colCtxMenu = uicontextmenu(fig);
    s.miColSortAsc  = uimenu(colCtxMenu, 'Text', 'Sort Ascending', ...
        'MenuSelectedFcn', @(~,~) []);
    s.miColSortDesc = uimenu(colCtxMenu, 'Text', 'Sort Descending', ...
        'MenuSelectedFcn', @(~,~) []);
    s.miColSetX     = uimenu(colCtxMenu, 'Text', 'Set as X-Axis', ...
        'Separator', 'on', 'MenuSelectedFcn', @(~,~) []);
    s.miColPlotY    = uimenu(colCtxMenu, 'Text', 'Plot as Y', ...
        'MenuSelectedFcn', @(~,~) []);
    s.miColStats    = uimenu(colCtxMenu, 'Text', 'Column Statistics', ...
        'Separator', 'on', 'MenuSelectedFcn', @(~,~) []);
    s.miColFormula  = uimenu(colCtxMenu, 'Text', 'New Column from Formula', ...
        'MenuSelectedFcn', @(~,~) []);
    s.tblUnits.ContextMenu = colCtxMenu;

    % ── Editable data table (pure numeric — big scroll-perf win) ─────────
    s.tblData = uitable(s.dataTableInnerGL, ...
        'Tag', 'BosonDataTable', ...
        'ColumnName', {'(no data)'}, ...
        'Data', [], ...
        'ColumnEditable', true, ...
        'CellEditCallback', @(~,~) [], ...
        'CellSelectionCallback', @(~,~) [], ...
        'FontSize', tk.font.body, ...
        'BackgroundColor', tk.color.bgInput, ...
        'ForegroundColor', tk.color.text);

    % ── Right-click context menu for row-level masking ────────────────────
    % Replaces the old "Masked" column.  Selected rows are taken from
    % appData.tableSelection which onTableSelectionChanged maintains from
    % the CellSelectionCallback.  MenuSelectedFcn wired by caller after
    % tableCallbacks struct is built.
    tblCtxMenu = uicontextmenu(fig);
    s.miMaskRows   = uimenu(tblCtxMenu, 'Text', 'Mask selected rows', ...
        'MenuSelectedFcn', @(~,~) []);
    s.miUnmaskRows = uimenu(tblCtxMenu, 'Text', 'Unmask selected rows', ...
        'MenuSelectedFcn', @(~,~) []);
    s.miUnmaskAll  = uimenu(tblCtxMenu, 'Separator', 'on', 'Text', 'Unmask all', ...
        'MenuSelectedFcn', @(~,~) []);
    s.tblData.ContextMenu = tblCtxMenu;
    s.tblData.Layout.Row = 5;
end
