function drawFitWindowOverlay(ax, xLo, xHi, label)
%DRAWFITWINDOWOVERLAY  Paint a translucent rect spanning [xLo, xHi] on ax.
%   Tagged 'peakFitWindow' so onClearOverlays / next fit can sweep it.
    if ~isvalid(ax) || ~isfinite(xLo) || ~isfinite(xHi) || xHi <= xLo
        return;
    end
    yLim = ax.YLim;
    h = patch(ax, ...
        'XData', [xLo xHi xHi xLo], ...
        'YData', [yLim(1) yLim(1) yLim(2) yLim(2)], ...
        'FaceColor', [0.85 0.20 0.20], ...
        'FaceAlpha', 0.10, ...
        'EdgeColor', [0.85 0.20 0.20], ...
        'EdgeAlpha', 0.55, ...
        'LineStyle', '--', ...
        'LineWidth', 1.0, ...
        'HitTest',  'off', ...
        'PickableParts', 'none', ...
        'Tag', 'peakFitWindow');
    h.HandleVisibility = 'off';
    if nargin >= 4 && ~isempty(label)
        text(ax, (xLo + xHi) / 2, yLim(2), label, ...
            'VerticalAlignment','top', 'HorizontalAlignment','center', ...
            'Color',[0.85 0.20 0.20], 'FontSize', 9, 'FontWeight','bold', ...
            'Tag','peakFitWindow', 'HitTest','off', 'PickableParts','none', ...
            'HandleVisibility','off');
    end
end
