function outFig = createOutFig(name, globalOpts)
%CREATEOUTFIG  Build the output figure for any Figure Builder generator.
%   Sized to globalOpts.figureWidth/Height in inches, white background,
%   and ready for tiledlayout / axes children.
    outFig = figure( ...
        'Name', name, ...
        'NumberTitle', 'off', ...
        'Units', 'inches', ...
        'Position', [1, 1, globalOpts.figureWidth, globalOpts.figureHeight], ...
        'Color', 'white', ...
        'PaperPositionMode', 'auto');
end
