function exportOriginScript(data, scriptPath, options)
%EXPORTORIGINSCRIPT  Export data as a LabTalk (.ogs) script for Origin import.
%
%   utilities.exportOriginScript(data, 'output.ogs')
%   utilities.exportOriginScript(data, 'output.ogs', 'CSVPath', 'data.csv')
%
%   Writes a LabTalk script that, when executed in OriginPro, imports the
%   accompanying CSV file, sets column designations (X/Y/yErr), applies
%   long names and units, formats axes, and optionally builds a graph.
%
%   This is a more maintainable alternative to writing binary .opju files
%   and does not require Origin to be running during export.
%
%   INPUTS:
%       data       — unified data struct (.time, .values, .labels, .units, .metadata)
%       scriptPath — output path for the .ogs script file
%
%   OPTIONAL NAME-VALUE PAIRS:
%       CSVPath    — path to the CSV data file; if empty, writes one alongside the script
%       BookName   — Origin workbook name (default: derived from source filename)
%       SheetName  — Origin worksheet name (default: derived from source filename)
%       LogX       — set X axis to log scale (default: false)
%       LogY       — set Y axis to log scale (default: false)
%       MakeGraph  — auto-create a graph after import (default: true)
%
%   EXAMPLE:
%       data = parser.importAuto('sample.dat');
%       utilities.exportOriginScript(data, 'sample.ogs');
%       % Then in Origin: run.file("sample.ogs");
%
%   See also utilities.toOrigin, utilities.writeXRDcsv

    arguments
        data                  (1,1) struct
        scriptPath            (1,1) string
        options.CSVPath       (1,1) string  = ""
        options.BookName      (1,1) string  = ""
        options.SheetName     (1,1) string  = ""
        options.LogX          (1,1) logical = false
        options.LogY          (1,1) logical = false
        options.MakeGraph     (1,1) logical = true
    end

    % ── Derive names from metadata ──────────────────────────────────────
    [scriptDir, scriptBase, ~] = fileparts(char(scriptPath));
    if isempty(char(options.BookName))
        if isfield(data, 'metadata') && isfield(data.metadata, 'source')
            [~, bookName, ~] = fileparts(data.metadata.source);
        else
            bookName = scriptBase;
        end
    else
        bookName = char(options.BookName);
    end

    if isempty(char(options.SheetName))
        sheetName = bookName;
    else
        sheetName = char(options.SheetName);
    end

    % Sanitise for LabTalk
    bookName  = regexprep(bookName,  '[^\w]', '_');
    sheetName = regexprep(sheetName, '[^\w]', '_');

    % ── Write CSV data file ─────────────────────────────────────────────
    if isempty(char(options.CSVPath))
        csvPath = fullfile(scriptDir, [scriptBase, '_data.csv']);
    else
        csvPath = char(options.CSVPath);
    end

    % Build header + data matrix
    xName = 'X';  xUnit = '';
    if isfield(data, 'metadata')
        m = data.metadata;
        if isfield(m, 'xColumnName') && ~isempty(m.xColumnName), xName = char(m.xColumnName); end
        if isfield(m, 'xColumnUnit') && ~isempty(m.xColumnUnit), xUnit = char(m.xColumnUnit); end
    end

    nYCols = size(data.values, 2);
    headers = [{xName}, data.labels];
    units   = [{xUnit}, data.units];

    fid = fopen(csvPath, 'w');
    if fid < 0
        error('utilities:exportOriginScript:fileOpen', 'Cannot write CSV: %s', csvPath);
    end
    cleanObj = onCleanup(@() fclose(fid));

    fprintf(fid, '%s\n', strjoin(headers, ','));
    fprintf(fid, '%s\n', strjoin(units, ','));

    mat = [data.time(:), data.values];
    for r = 1:size(mat, 1)
        fprintf(fid, '%s\n', strjoin(arrayfun(@(v) sprintf('%.10g', v), mat(r,:), 'UniformOutput', false), ','));
    end
    clear cleanObj;  % flush and close

    % ── Write LabTalk script ────────────────────────────────────────────
    fid = fopen(scriptPath, 'w');
    if fid < 0
        error('utilities:exportOriginScript:fileOpen', 'Cannot write script: %s', scriptPath);
    end
    cleanObj2 = onCleanup(@() fclose(fid));

    fprintf(fid, '// LabTalk script generated by thin_film_toolkit_matlab\n');
    fprintf(fid, '// Date: %s\n\n', datestr(now, 'yyyy-mm-dd HH:MM:SS')); %#ok<TNOW1,DATST>

    % Import CSV
    [~, csvFn, csvExt] = fileparts(csvPath);
    fprintf(fid, '// Import data\n');
    fprintf(fid, 'newbook name:="%s" sheet:=1;\n', bookName);
    fprintf(fid, 'wks.name$ = "%s";\n', sheetName);
    fprintf(fid, 'impASC fname:="%s" options.SkipRows.Count:=2;\n\n', [csvFn, csvExt]);

    % Set column designations
    fprintf(fid, '// Column designations and labels\n');
    fprintf(fid, 'wks.col1.type = 4;  // X\n');
    fprintf(fid, 'wks.col1.lname$ = "%s";\n', escapeLT(xName));
    fprintf(fid, 'wks.col1.unit$ = "%s";\n', escapeLT(xUnit));

    for k = 1:nYCols
        cn = k + 1;
        lbl = char(data.labels{k});
        unt = char(data.units{k});
        if contains(lower(lbl), {'err', 'dr', 'std', 'sigma'})
            fprintf(fid, 'wks.col%d.type = 3;  // yErr\n', cn);
        else
            fprintf(fid, 'wks.col%d.type = 1;  // Y\n', cn);
        end
        fprintf(fid, 'wks.col%d.lname$ = "%s";\n', cn, escapeLT(lbl));
        fprintf(fid, 'wks.col%d.unit$ = "%s";\n', cn, escapeLT(unt));
    end

    % Graph creation
    if options.MakeGraph
        fprintf(fid, '\n// Create graph\n');
        fprintf(fid, 'plotxy iy:=(1,2) plot:=201 ogl:=[<new>];\n');
        if options.LogX
            fprintf(fid, 'layer.x.type = 1;  // Log X\n');
        end
        if options.LogY
            fprintf(fid, 'layer.y.type = 1;  // Log Y\n');
        end
        fprintf(fid, 'xb.text$ = "%s";\n', escapeLT([xName, guiTernary(isempty(xUnit), '', [' (', xUnit, ')'])]));
        if nYCols == 1
            yLabel = [char(data.labels{1}), guiTernary(isempty(char(data.units{1})), '', [' (', char(data.units{1}), ')'])];
            fprintf(fid, 'yl.text$ = "%s";\n', escapeLT(yLabel));
        end
    end

    fprintf(fid, '\n// Done\n');
end


function s = escapeLT(str)
%ESCAPELT  Escape double-quotes for LabTalk string literals.
    s = strrep(str, '"', '\"');
end

function r = guiTernary(cond, a, b)
    if cond, r = a; else, r = b; end
end
