function out = generateExtraction(filePath, startLine, endLine, functionName, opts)
% Generate complete extraction artifacts: build function + caller replacement.
%
%   out = scripts.generateExtraction('BosonPlotter.m', 1042, 1165, 'buildAxesContextMenu')
%   out = scripts.generateExtraction('FermiViewer.m', 500, 800, 'buildAnnotationsPanel', Package="+emViewer")
%
% Writes to disk:
%   +bosonPlotter/<functionName>.m   (the extracted function)
%   extraction_caller_<name>.m       (caller-side replacement snippet)
%
% The generated files need manual review — they're 90% correct scaffolds
% that still need:
%   1. Callback struct field naming cleanup
%   2. Verify parent arg matches actual container
%   3. Remove dead closure reads (false positives from identifier scan)
%   4. Run tests

    arguments
        filePath     (1,1) string
        startLine    (1,1) double
        endLine      (1,1) double
        functionName (1,1) string
        opts.Package (1,1) string = "+bosonPlotter"
        opts.DryRun  (1,1) logical = false
    end

    inv = scripts.extractionInventory(filePath, startLine, endLine, Verbose=true);

    lines = cellstr(readlines(filePath));
    block = lines(startLine:endLine);

    % ── Classify closure reads ───────────────────────────────────────
    % Group them: parent containers, color/token constants, callback handles, other
    parents = inv.parentRefs;
    callbacks = inv.callbackRefs;
    reads = inv.closureReads;

    colorTokens = reads(contains(reads, {'BTN_','FG','BG','tk','palette','PALETTE', ...
        'COLOR','color','Color','FONT','font','ICON','icon'}));
    otherReads = setdiff(reads, [parents(:); colorTokens(:)]);

    % ── Generate build function ──────────────────────────────────────
    bld = {};
    bld{end+1} = sprintf('function s = %s(parent, tk, palette, callbacks)', functionName);
    bld{end+1} = sprintf('%%%% %s  Extracted UI construction block.', upper(functionName));
    bld{end+1} = '%';
    bld{end+1} = sprintf('%%   Lines %d–%d of %s', startLine, endLine, filePath);
    bld{end+1} = sprintf('%%   Generated by scripts.generateExtraction on %s', datetime('today'));
    bld{end+1} = '%';
    bld{end+1} = '% Args:';
    bld{end+1} = '%   parent    — parent uigridlayout / uipanel';
    bld{end+1} = '%   tk        — UX tokens from bosonPlotter.uxTokens()';
    bld{end+1} = '%   palette   — button color palette struct';
    bld{end+1} = '%   callbacks — struct of function handles (see below)';
    bld{end+1} = '%';
    bld{end+1} = '% Required callback fields:';
    for i = 1:numel(callbacks)
        bld{end+1} = sprintf('%%   .%s', callbacks{i});
    end
    bld{end+1} = '%';
    bld{end+1} = '% Returns struct with widget handles.';
    bld{end+1} = '';

    % Unpack color tokens
    if ~isempty(colorTokens)
        bld{end+1} = '    % ── Unpack palette/tokens ──';
        for i = 1:numel(colorTokens)
            bld{end+1} = sprintf('    %s = palette.%s;', colorTokens{i}, colorTokens{i});
        end
        bld{end+1} = '';
    end

    % Unpack other closure reads (mark as TODO for manual review)
    if ~isempty(otherReads)
        bld{end+1} = '    % ── TODO: These closure reads need manual routing ──';
        bld{end+1} = '    % (pass via callbacks struct, palette, or function args)';
        for i = 1:numel(otherReads)
            bld{end+1} = sprintf('    %% NEEDS: %s', otherReads{i});
        end
        bld{end+1} = '';
    end

    % Replace parent variable names in the block
    primaryParent = '';
    if ~isempty(parents)
        primaryParent = parents{1};
    end

    bld{end+1} = '    % ═══════════ EXTRACTED BLOCK ═══════════';
    for i = 1:numel(block)
        ln = block{i};
        % Replace the primary parent variable with 'parent'
        if ~isempty(primaryParent)
            ln = regexprep(ln, sprintf('\\b%s\\b', primaryParent), 'parent');
        end
        bld{end+1} = ln;
    end
    bld{end+1} = '    % ═══════════ END EXTRACTED BLOCK ═══════════';
    bld{end+1} = '';

    % Return struct
    returnFields = unique([inv.widgetHandles(:); inv.closureWrites(:)]);
    bld{end+1} = '    % ── Build return struct ──';
    if isempty(returnFields)
        bld{end+1} = '    s = struct();';
    else
        bld{end+1} = '    s = struct( ...';
        for i = 1:numel(returnFields)
            sep = ', ...';
            if i == numel(returnFields), sep = ' ...'; end
            bld{end+1} = sprintf('        ''%s'', %s%s', returnFields{i}, returnFields{i}, sep);
        end
        bld{end+1} = '    );';
    end
    bld{end+1} = 'end';
    buildCode = strjoin(bld, newline);

    % ── Generate caller-side replacement ─────────────────────────────
    shortName = char(functionName);
    if startsWith(shortName, 'build')
        shortName = shortName(6:end);
        shortName(1) = lower(shortName(1));
    end
    pkgName = char(opts.Package);
    if startsWith(pkgName, '+')
        pkgName = pkgName(2:end);
    end

    cal = {};
    cal{end+1} = '';
    cal{end+1} = sprintf('    %% ── %s (extracted) ──', functionName);

    % Build callbacks struct
    if ~isempty(callbacks)
        cal{end+1} = sprintf('    %sCb_ = struct( ...', shortName);
        for i = 1:numel(callbacks)
            sep = ', ...';
            if i == numel(callbacks), sep = ' ...'; end
            cal{end+1} = sprintf('        ''%s'', @%s%s', callbacks{i}, callbacks{i}, sep);
        end
        cal{end+1} = '    );';
    end

    % Build palette passthrough (if color tokens found)
    if ~isempty(colorTokens)
        cal{end+1} = sprintf('    %sPal_ = struct( ...', shortName);
        for i = 1:numel(colorTokens)
            sep = ', ...';
            if i == numel(colorTokens), sep = ' ...'; end
            cal{end+1} = sprintf('        ''%s'', %s%s', colorTokens{i}, colorTokens{i}, sep);
        end
        cal{end+1} = '    );';
    end

    % Call
    palArg = 'palette';
    if ~isempty(colorTokens)
        palArg = sprintf('%sPal_', shortName);
    end
    cbArg = 'struct()';
    if ~isempty(callbacks)
        cbArg = sprintf('%sCb_', shortName);
    end
    parentArg = 'parent';
    if ~isempty(primaryParent)
        parentArg = primaryParent;
    end
    cal{end+1} = sprintf('    %sUI_ = %s.%s(%s, tk, %s, %s);', ...
        shortName, pkgName, functionName, parentArg, palArg, cbArg);

    % Unpack returns
    for i = 1:numel(returnFields)
        cal{end+1} = sprintf('    %s = %sUI_.%s;', returnFields{i}, shortName, returnFields{i});
    end
    callerCode = strjoin(cal, newline);

    % ── Output ───────────────────────────────────────────────────────
    out.buildCode   = buildCode;
    out.callerCode  = callerCode;
    out.inventory   = inv;
    out.returnFields = returnFields;

    % ── Write files (unless dry run) ─────────────────────────────────
    if ~opts.DryRun
        buildPath = fullfile(opts.Package, [char(functionName) '.m']);
        callerPath = fullfile('extraction_output', ...
            sprintf('caller_%s.m', functionName));

        if ~exist('extraction_output', 'dir')
            mkdir('extraction_output');
        end

        writelines(buildCode, buildPath);
        writelines(callerCode, callerPath);

        fprintf('\n  ★ Written:\n');
        fprintf('    BUILD:  %s\n', buildPath);
        fprintf('    CALLER: %s\n', callerPath);
        fprintf('\n  Next steps:\n');
        fprintf('    1. Review %s — fix closure reads marked TODO\n', buildPath);
        fprintf('    2. Replace lines %d–%d in %s with caller snippet\n', ...
            startLine, endLine, filePath);
        fprintf('    3. Run: runAllTests(Group="gui")\n');
        fprintf('    4. Ratchet LINE_CEILING in test_bosonPlotterSize.m\n');
        fprintf('\n');
    else
        fprintf('\n  [DRY RUN] Would write to %s/%s.m\n', opts.Package, functionName);
    end
end
